### ISSUE TITLE
Widget中设置grid.span后，全部部件都被修改。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2101]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-pkar6z?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-pkar6z?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
如Demo中，已设置默认的span为12。
```ui: {
      '*': {
        grid: {
          span: 12,
        },
      },
    },
```
当在自定义的小部件中，使用 `this.ui.grid!.span = 24;` 时，所有的小部件的span均被改为24了。

### What is expected?
自定义小部件中修改ui属性时仅修改当前小部件。

### What is actually happening?
影响到了其他的小部件。

| Environment | Info |
|---|---|
| ng-alain | 12.2.2 |
| Browser | all |

**Comment by cipchk** [comment]
可以临时给 `age.ui` 增加一个空的 `grid` 破坏这种关系。
