### ISSUE TITLE
表格组件增加不自动载入数据开关。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2103]
## What problem does this feature solve?
很多情况下，都需要对输入的数据进入处理，然后再做为请求参数，向后端请求数据。
特别是当表格的结构是通过传入的数据控制的情况下，这种情况更为常见。

目前表格载入后，直接就向后端发起了请求。
如果能够设置一个开关。在数据传入并处理完后再开始载入数据，可以节省很多的工作量。

## What does the proposed API look like?
给表格增加一个不自动载入数据的选项。

**Comment by wyq-L** [comment]
lazyLoad: true 就能实现，官网有说明

**Comment by xingkoo** [comment]
@wyq-L 感谢。
