### ISSUE TITLE
基于@delon/form的可视化编辑器

### ISSUE THREAD

**Issue by qgzhao** [cipchk/ng-alain#2105]
## What problem does this feature solve?
@delon/form已经非常强大了，但美中不足还差一个比较好用的可视化编辑器，实现拖放生成表单并可视化配置组件，功能类似于：https://form.lljj.me/

## What does the proposed API look like?
@delon/form/editor

**Comment by cipchk** [comment]
精力有限，目前没有这方面的计划，欢迎补充。
