### ISSUE TITLE
Angular 12: ng add ng-alain schematics don't take into consideration angular workspace

### ISSUE THREAD

**Issue by prabh-62** [cipchk/ng-alain#2106]
### Reproduction link
[https://stackblitz.com](https://stackblitz.com)

### Steps to reproduce
I cannot provide a link to minimal reproduction since the issue is with `ng add` schematics

Generate an angular workspace and add ng-alain before starting dev-server
```shell
npx @angular/cli@12 new web-apps --create-application false
cd web-apps
yarn ng generate application admin-console --prefix ac --style scss
yarn ng add ng-alain #--project admin-console
yarn start
```

### What is expected?
Google chrome browser should launch with working angular application

### What is actually happening?
Errors appear in terminal regarding missing imports, etc.
<img width="1391" alt="angular_errors_ng-alain_paths_tsconfig" src="https://user-images.githubusercontent.com/13006107/134784844-94ee7b4b-2c6c-4643-8e1d-2b7416721245.png">

| Environment | Info |
|---|---|
| ng-alain | 12.2.3 |
| Browser | Chrome 93 |
```
Angular CLI: 12.2.7
Node: 16.10.0
Package Manager: yarn 1.22.11
OS: darwin x64

Angular: 12.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.7
@angular-devkit/build-angular   12.2.7
@angular-devkit/core            12.2.7
@angular-devkit/schematics      12.2.7
@schematics/angular             12.2.7
rxjs                            6.6.7
typescript                      4.3.5
```

---
Fix `paths` in `tsconfig.json` and application should run without any errors
<img width="581" alt="angular_errors_ng-alain_paths_tsconfig_fix" src="https://user-images.githubusercontent.com/13006107/134784872-b7d9f18e-9701-43ed-a897-e45d3845f806.png">

**Comment by cipchk** [comment]
You can try the following steps:

```
npx @angular/cli@12 new web-apps --create-application false
cd web-apps
yarn ng add ng-alain #--project admin-console
yarn ng generate application admin-console --prefix ac --style scss
yarn start
```

**Comment by prabh-62** [comment]
I don't understand. I actually tried the exact steps as mentioned and I ran into the issue. The steps you mentioned in the reply are exactly what I described earlier.

**Comment by cipchk** [comment]
@prabh-62 This is indeed the case, mainly because `ng add ng-alain` needs to depend on `ng new app` instead of `ng new app --create-application false`
