### ISSUE TITLE
st组件ps=0时死循环内存溢出UI卡死

### ISSUE THREAD

**Issue by tky753** [cipchk/ng-alain#2107]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-8t85yp?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-8t85yp?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击 “set ps 0"按钮

### What is expected?
抛出异常，停止加载组件，提示ps必须大于0

### What is actually happening?
死循环内存溢出，UI卡死

| Environment | Info |
|---|---|
| ng-alain | 12.2.2 |
| Browser | edge 版本 94.0.992.31 |

---
直接UI卡死体验太差，调试了半天才找出来，希望能优化错误提示。

**Comment by cipchk** [comment]
是 `nz-table` 引起的，可以至 ng-zorro-antd 提交issues。
