### ISSUE TITLE
能否给所有的SF组件中Widget增加change事件

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2119]
## What problem does this feature solve?
radio,select 等组件中当值发生变化可以触发ui.change事件，可以根据这些值做一些处理。
而类似Number，并没有触发到change事件。在一些场景下是需要对用户输入的值做一定处理的。

## What does the proposed API look like?
所有类似Number的Widget都可以触发ui.change事件。

**Comment by cipchk** [comment]
不管是radio还是select都有change，并且都会有相应的触发，见 ：https://ng-alain.com/form/radio/en#Examples

**Comment by xingkoo** [comment]
是的，radio和select确实增加了change事件。但是Number发生变化时却没有change事件触发。
当我修改数值时，需要根据数值计算，得到一个结果，并反馈给用户。而number组件却不能让我直接使用。我需要重新定制一个组件来处理这个问题。
我使用的场景是价格转换。用户录入一个价格后，根据他录入的价格，需要计算出不同的时间单位下的价格。

**Comment by cipchk** [comment]
@xingkoo `formValueChange` 也可以实现，不过我依然会给 `number` 增加 `change` 事件。

**Comment by xingkoo** [comment]
辛苦卡色大大。
