### ISSUE TITLE
support build with pnpm

### ISSUE THREAD

**Issue by tky753** [cipchk/ng-alain#2127]
## What problem does this feature solve?
windows下用pnpm编译的时候会包缺少一些包，因为这些包是间接引用的，但我引用后又报其他错误了。

## What does the proposed API look like?
想要用pnpm的工作空间实现monorepo，如果能提供pnpm的编译支持，就太好了

**Comment by cipchk** [comment]
麻烦提供一下编译错误的具体细节。

**Comment by tky753** [comment]
@cipchk  大部分less编译错误，貌似是路径问题。
![image](https://user-images.githubusercontent.com/18205977/140641762-149a6051-e1ef-4d37-8af9-152948a3905e.png)

因为缺少直接引用pnpm会找不到引用，所以我又手动安装了@ant-design/colors、@ant-design/icons-angular、@angular/cdk、date-fns、extend，可能版本不对？
你可以删掉 node_modules 目录，再安装pnpm，运行`pnpm i`，之后运行`pnpm start`就可以看到错误信息了，因为太长了.
我建议还是自己去运行，然后看看错误信息吧

**Comment by cipchk** [comment]
看路径我大概知道，pnpm 跟 cnpm 原理类似，都会导致 `node_modules` 实际依赖包名称变动，细节可以参考：https://ng-alain.com/docs/faq/zh?#%E5%AE%89%E8%A3%85

**Comment by tky753** [comment]
@cipchk  less路径问题，通过把 `@import "~@delon` 改成 类似`import "../../node_modules/@delon`就解决问题了
