### ISSUE TITLE
设置sf中某个字段的样式

### ISSUE THREAD

**Issue by insov** [cipchk/ng-alain#2128]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-ptnvgr?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-ptnvgr?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
根据<https://ng-alain.com/form/schema/zh> 
> [class] 自定义类，等同 [ngClass] 值。
设置name 的 class text-red，页面上name字段颜色没有变化

### What is expected?
name字段的标签以及输入框的样式应该符合class

### What is actually happening?
无效

| Environment | Info |
|---|---|
| ng-alain | 12.3.0 |
| Browser | Microsoft Edge 95.0.1020.44 |

**Comment by insov** [comment]
查看页面内容，sf-string 的样式已经被覆盖了 
![image](https://user-images.githubusercontent.com/3804453/140720622-f568b253-3593-40ff-b32e-787dfe61f5fb.png)

**Comment by cipchk** [comment]
暂时没有更好的办法，你可以重新定义一下：

```ts
import { Component } from '@angular/core';
import { SFSchema } from '@delon/form';

@Component({
  selector: 'my-app',
  template: `

    <sf [schema]="schema"></sf>

    `,
    styles: [
      `
      :host ::ng-deep .name-label .sf__label-text {
        color: #f50;
      }
      `
    ]
})
export class AppComponent {

  schema:SFSchema = {
    properties: {
      "name": {
        type: "string",
        ui:{
          class:'name-label'
        }
      },
      password: {
        type: "string",
        ui: {
          type: "password"
        }
      }
    },
    required: ["name", "password"]
  };

}
```
