### ISSUE TITLE
select组件tags模式选择数据提示不应少于一个项 并且 还不能设置默认值

### ISSUE THREAD

**Issue by beibei-Young** [cipchk/ng-alain#2131]
schema: SFSchema = {
    properties: {
      userId: { type: 'string', title: '班组下的人' },
    },
  };

$userId: {
      widget: 'select',
      mode: 'tags',
      grid: { span: 24 },
      asyncData: () =>     this.http.get(`api/biz/modRole/listByBizId/${this.params?.modelId}`).pipe(pluck('data'))
    },

![image](https://user-images.githubusercontent.com/45983418/141394291-4b7f576a-8029-436d-9e23-4bcba7677d46.png)

**Comment by cipchk** [comment]
@beibei-Young 能否提供完整的重现示例，其中 `this.http.get` 可以使用 `of([])` 来代替。

**Comment by beibei-Young** [comment]
![image](https://user-images.githubusercontent.com/45983418/141401452-8630f57b-8990-4230-9f6c-3f8d1d42ec61.png)
![GS0 XWF@0T}@R0VA506XDNG](https://user-images.githubusercontent.com/45983418/141401542-7a81e705-b9f0-4560-97ee-7518a47d0b89.png)

**Comment by beibei-Young** [comment]
他这个我返回数据达到要求，就是会报这个问题，然后还有好像不支持默认值

**Comment by cipchk** [comment]
Json Schema 标准里面 `enum` 至少要有一个值以上，我不理解你为什么这里会有一个空的 `enum: []` 是出于什么原因加上的？可以尝试移除看是否解决。

**Comment by beibei-Young** [comment]
这里的空我本来是想后面动态的加上去然后reset，但是我试了不行

**Comment by beibei-Young** [comment]
后来我用官网实例数据放进enum里，并且设置default，默认值并不能显示出来

**Comment by beibei-Young** [comment]
他这里爆红确实是因为我这个空的enum引起的

**Comment by cipchk** [comment]
抱歉，这样讨论完全没有任何意义 ，麻烦提供一个在线 stackblitz 重现示例。

**Comment by beibei-Young** [comment]
![image](https://user-images.githubusercontent.com/45983418/141404325-ddf672cd-6a60-4a33-a7cb-2d50e53f441d.png)

**Comment by cipchk** [comment]
@beibei-Young 抱歉，你能否提供一个完整的 stackblitz 重现链接地址，我无法依旧你一点点挤牙膏似的，一点点判断，这对我而言太浪费时间，这也许只是一个非常简单的问题，但前提是你需要有个一个重现链接，对我们双方能快速解决这一问题是一个非常重要的东西，至少在重现链接里面，我们看到的东西是完全一致的。
