### ISSUE TITLE
app目录下的routes目录希望可以允许自定义修改，如pages

### ISSUE THREAD

**Issue by xylplm** [cipchk/ng-alain#2134]
## What problem does this feature solve?
app目录下的routes目录希望可以允许自定义修改，如pages。自己之前做的很多项目，包括现在公司的项目，业务代码都是放在pages目录下，所以更习惯这个这个名字。

## What does the proposed API look like?
有配置来定义

**Comment by aLoNeIT** [comment]
What problem does this feature solve?
同楼主需求，但是希望能更进一步做成多应用模式，每个原routes目录下都有完整的子级目录，这样方便将不同管理后台写在一个项目当中。

What does the proposed API look like?
有配置来定义
