### ISSUE TITLE
g2-radar 能否增加一个最大最小值参数支持

### ISSUE THREAD

**Issue by zhouyingqiu** [cipchk/ng-alain#2139]
## What problem does this feature solve?
百分比指标比较的时候需要固定最大值为100%

## What does the proposed API look like?
// G2原本的雷达图可以这样设置
chart.scale([key], {
  min: 0,
  max: 80,
});

**Comment by cipchk** [comment]
`min`或`max` 只是定义域的大小，数据是多少他依然会渲染多大，建议从数据中限定。

**Comment by zhouyingqiu** [comment]
这个不是数据的问题，就是不同维度百分比大小比较的时候想要看到的效果是轴的区间始终是0-100，而不是按现在的逻辑，数据里最大值是多少轴的最大值就是多少

**Comment by cipchk** [comment]
@zhouyingqiu 能否提供一下 G2 的在线解决问题的示例（或者使用 `g2-custom` 提供一个自定义 stackblitz 解决示例），我在 G2 官网的确没有找到相应接口。
