### ISSUE TITLE
建议统一页面滚动条与表格，card等滚动条CSS样式

### ISSUE THREAD

**Issue by xylplm** [cipchk/ng-alain#2148]
## What problem does this feature solve?
现在ng-alain页面滚动条是使用黑色圆角，浅灰色背景的滚动条。而table等控件滚动条，却用的NG-ZORRO样式的滚动条。
建议如果ng-alain使用有自己特色的滚动条样式，那么可以覆盖到NG-ZORRO的控件滚动条。

## What does the proposed API look like?
统一CSS样式

**Comment by xylplm** [comment]
![页面滚动条](https://user-images.githubusercontent.com/49856280/142732967-f0498ef0-d475-4b9a-929e-be46ee5cfe6e.png)
![表格滚动条](https://user-images.githubusercontent.com/49856280/142732980-8d2dd6b1-8bcf-49cc-a1fe-3163bd580f33.png)
如上图所示，表格等控件样式与页面样式并不一致

**Comment by cipchk** [comment]
当前表现都一致：https://ng-alain.gitee.io/#/delon/st  

GIF:

![demo](https://user-images.githubusercontent.com/2987467/150158716-3910d92f-5621-4f57-ac77-45d8369cba46.gif)
