### ISSUE TITLE
doocument has some error

### ISSUE THREAD

**Issue by devcui** [cipchk/ng-alain#2149]
### Reproduction link
[https://github.com/ng-alain/delon/blob/master/schematics/docs/generate.zh-CN.md](https://github.com/ng-alain/delon/blob/master/schematics/docs/generate.zh-CN.md)

### Steps to reproduce
ng g ng-alain:trade       

An unhandled exception occurred: Schematic "trade" not found in collection "ng-alain".
See "/private/var/folders/08/_1t5_7kn34zddcpy5nrzkb780000gn/T/ng-JnUwVW/angular-errors.log" for further details.

### What is expected?
success

### What is actually happening?
failed

| Environment | Info |
|---|---|
| ng-alain | 12.4.1 |
| Browser | Chrome |

---

https://github.com/ng-alain/delon/blob/433353f378fa8791b8b24ef051d736e6456a079f/schematics/docs/generate.zh-CN.md?plain=1#L38

**Comment by hidoos** [comment]
这应该文档是不小心写错了吧，还是原来的 `command` 的
