### ISSUE TITLE
withoutModulePrefixInComponentName can not work

### ISSUE THREAD

**Issue by devcui** [cipchk/ng-alain#2150]
### Reproduction link
[https://github.com/ng-alain/delon/blob/master/schematics/utils/alain.ts#L72](https://github.com/ng-alain/delon/blob/master/schematics/utils/alain.ts#L72)

### Steps to reproduce
ng g ng-alain:list list -m=trade -withoutModulePrefixInComponentName=true

output: `NOTE: The "dryRun" flag means no changes were made.`

### What is expected?
command can successed

### What is actually happening?
command failed

| Environment | Info |
|---|---|
| ng-alain | 12.4.1 |
| Browser | Chrome |

---
大概是没开发完成呢？

**Comment by cipchk** [comment]
使用 `--withoutModulePrefixInComponentName` 而非 `-withoutModulePrefixInComponentName`，文档上的错误
