### ISSUE TITLE
建议sf对于mode=“"search"表单，提供属性，可以过滤掉null、undefind、空字符串等无效值

### ISSUE THREAD

**Issue by xylplm** [cipchk/ng-alain#2151]
## What problem does this feature solve?
如果是mode为search，建议可以提供一个属性开关，来过滤掉null、undefind、空字符串等这些明确的无效值。因为大多数场景的搜索表单，都只需要有效值。

## What does the proposed API look like?
建议可以对mode为search的表单允许过滤无效值属性开关或者配置过滤类型。

**Comment by cipchk** [comment]
若需要统一处理，建议在拦截器中处理，若是使用 `_HttpClient` 也可以配置 `nullValueHandling` 参数为 `ingore`（默认为：`include`）。
