### ISSUE TITLE
SF验证器数组配置

### ISSUE THREAD

**Issue by Diluka** [cipchk/ng-alain#2153]
## What problem does this feature solve?
按一定顺序应用多个验证器

## What does the proposed API look like?
```ts
type Validator = (value: SFValue, formProperty: FormProperty, form: PropertyGroup) => ErrorData[] | Observable<ErrorData[]>

// 现有的属性
validator?: Validator| Validator[]
```

**Comment by cipchk** [comment]
麻烦提供一下更多细节，当前的现状是怎么样，期望结果是什么？

**Comment by Diluka** [comment]
目前只能传一个验证函数，我现在有一个封装好的验证函数，然后仅某处需要新增一个。希望这个验证函数可以配置一个数组，里面是一个一个独立的验证函数，验证从数组第一个开始，如果不通过则停止后续验证。比如一个本地验证和一个异步验证器组合，格式不正确就不用发起异步验证了。
