### ISSUE TITLE
[form] date widget conflict with browser autocomplete feature

### ISSUE THREAD

**Issue by HsinM** [cipchk/ng-alain#2154]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-biiv4g?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-alain-setup-biiv4g?file=src/app/app.component.ts)

### Steps to reproduce
Click datepicker input box (if autocomplete has data and enabled at browser).

### What is expected?
Datepicker and autocomplete appear one at a time.

### What is actually happening?
Datepicker and autocomplete appear both at a time.

![image](https://user-images.githubusercontent.com/16590829/143778945-13f93e88-19bf-4b73-bc9b-a12ce9343f82.png)

| Environment | Info |
|---|---|
| ng-alain | 12.4.2 |
| Browser | 96.0.4664.45 (正式版本) (64 位元) (cohort: 96_win_45) 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947} |

---
Developer can control date widget [autocomplete] value schema ui object.

**Comment by cipchk** [comment]
See https://github.com/NG-ZORRO/ng-zorro-antd/issues/6718

**Comment by HsinM** [comment]
Thanks!

**Comment by cipchk** [comment]
fixed by ng-zorro-antd 12.1.1
