### ISSUE TITLE
[ng-alain] RTL and Fullscreen feature not working

### ISSUE THREAD

**Issue by HsinM** [cipchk/ng-alain#2156]
### Reproduction link
[https://ng-alain.surge.sh/#/dashboard/v1](https://ng-alain.surge.sh/#/dashboard/v1)

### Steps to reproduce
Click menu items.
![alain](https://user-images.githubusercontent.com/16590829/144471844-2bb8d491-8644-480e-94b6-a51869851cb8.gif)

### What is expected?
Active RTL or Fullscreen mode.

### What is actually happening?
Not response, but v11 working well.

| Environment | Info |
|---|---|
| ng-alain | 12.4.2 |
| Browser | 96.0.4664.45 (正式版本) (64 位元) (cohort: 96_win_45) 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947} |

**Comment by devcui** [comment]
maybe you can click the text( not blank)

**Comment by devcui** [comment]
If you want to fix it, you can bind the function to the entire region
