### ISSUE TITLE
咨询一下，有没有popover非Directive的实现的用法，类似懒加载效果，当我点击的时候，由服务动态创建浮层，而不是在html用directive绑定浮层

### ISSUE THREAD

**Issue by Freshfishfish** [cipchk/ng-alain#2159]
## What problem does this feature solve?
咨询一下，有没有popover非Directive的实现的用法，类似懒加载效果，当我点击的时候，由服务动态创建浮层，而不是在html用directive绑定浮层
例如提供一个服务，这样使用：
html:
<button (click)="popover($event)"></button>
ts:
popover($event:any){
    const popover=await this.popoverService.create({
          component:MyPopoverComponent,
          props:{text:"点我"}
    });
    popover.present();
}

因为我的界面上有上千个dom节点需要使用popover，如果全部用derective，界面会卡死

## What does the proposed API look like?
例如提供一个服务，这样使用：
html:
<button (click)="popover($event)"></button>
ts:
popover($event:any){
    const popover=await this.popoverService.create({
          component:MyPopoverComponent,
          props:{text:"点我"}
    });
    popover.present();
}

**Comment by xingkoo** [comment]
自己封装一个呀。类似：

```
import { Directive, ElementRef, EventEmitter, HostListener, Input, Output } from '@angular/core';
import { ModalHelper } from '@delon/theme';

@Directive({
  selector: '[Customize]'
})
export class CustomizeDirective {
  @Input() config!: config;
  @Output() readonly selected = new EventEmitter();
  constructor(private elementRef: ElementRef, private modal: ModalHelper) {}

  @HostListener('click')
  onClick(): void {
    this.modal
      .create(AComponent, {
        config: this.config,
        includeTabs: true
      })
      .subscribe((res: any) => {
        if (res) {
          this.selected.emit(res);
        }
      });
  }
}
```

使用时，
```
<a customize [config]="config" (selected)="selected($event)">test<a>
```
```
config = {a:1,b:2};
selected(res) {
    console.log(res);
}
```

**Comment by cipchk** [comment]
也可以参考 [onboarding](https://github.com/ng-alain/delon/blob/master/packages/abc/onboarding/onboarding.service.ts#L59) 的写法，核心的部分差不多如此。
