### ISSUE TITLE
PDF 无法显示PKCS#7数字签名

### ISSUE THREAD

**Issue by insov** [cipchk/ng-alain#2163]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-zn2gj4](https://stackblitz.com/edit/ng-alain-setup-zn2gj4)

### Steps to reproduce
打开后显示的PDF没有数字签名

### What is expected?
显示数字签名

### What is actually happening?
未显示数据签名

直接使用浏览器打开有数字签名
![image](https://user-images.githubusercontent.com/3804453/146160221-af82416f-a8ae-4d6a-b429-1366b156b567.png)

控件显示的没有数字签名
![image](https://user-images.githubusercontent.com/3804453/146160368-1fbf117f-1c31-4a4e-a639-a9f36ba73b7a.png)

| Environment | Info |
|---|---|
| ng-alain | 12.4.2 |
| Browser | Microsoft Edge 96.0.1054.53 |

---
pdf.js 在 v2.9.359后会显示数字签名。 
如果直接更新  pdf.js 类库的根路径 https://cdn.jsdelivr.net/npm/pdfjs-dist@2.11.338/  会报错

https://stackblitz.com/edit/ng-alain-setup-kcf6dc?file=src%2Fapp%2Fglobal-config.module.ts

Unhandled Promise rejection: The container must be absolutely positioned. ; Zone: <root> ; Task: Promise.then ; Value: Error: The container must be absolutely positioned.

**Comment by insov** [comment]
ng2-pdf-viewer 在 7.0.2中修复了

**Comment by cipchk** [comment]
修改一下全局配置里的 `lib` 为新版本的 PDF.js 就可以了。
