### ISSUE TITLE
se一行一列错误校验导致界面跳动

### ISSUE THREAD

**Issue by zegnanxi** [cipchk/ng-alain#2180]
### Reproduction link
[https://stackblitz.com/edit/nepwsd--run?file=src/app/app.component.ts](https://stackblitz.com/edit/nepwsd--run?file=src/app/app.component.ts)

### Steps to reproduce
App Secret输入框，输入a，然后删除a，这时提示必选（请填写，小于32位），再输入a，此时下方button往上跳动再返回。

### What is expected?
button不会跳动（以往版本，）

### What is actually happening?
button有个往上跳动的暂时状态，导致界面闪动。

| Environment | Info |
|---|---|
| ng-alain | 13.0.0 |
| Browser | chrome最新 |

**Comment by cipchk** [comment]
@zegnanxi 无法打开重现链接

**Comment by zegnanxi** [comment]
故障依然存在啊。官网例子，se，一行一列表单。先随意输入再清空，出现请输入提示。这时随便输入，提示消失，会跳跃一下。

**Comment by zegnanxi** [comment]
13.1.0 @cipchk

**Comment by cipchk** [comment]
@zegnanxi 能提供一个 gif 动画 吗？

**Comment by zegnanxi** [comment]
[url=https://sm.ms/image/5GktUnvFXSpaiwj][img]https://s2.loli.net/2022/01/20/5GktUnvFXSpaiwj.gif[/img][/url]
@cipchk
