### ISSUE TITLE
sf组件中新增单独渲染小部件的组件

### ISSUE THREAD

**Issue by rxxy** [cipchk/ng-alain#2182]
## What problem does this feature solve?
实现一个UI界面生成schema的功能，这个功能有2个使用场景：
1. 开发阶段使用图形界面生成schema粘贴到代码里，比直接写代码方便，效率高。
2. 使用工作流自定义审批表单和流程。

在实现动态生成schema时，我没有找到可以通过schema渲染单个小部件的组件(由于需要使用拖拽排序，所以必须是一个小部件一个组件)。
我通过WidgetFactory.createWidget方法去创建小部件时，得到了如下错误：
```
./src/app/routes/formbuilder/formbuilder.component.ts:5:0-71 - Error: Module not found: Error: Package path ./src/terminator.service is not exported from package D:\project\form-builder\node_modules\@delon\form (see exports field in D:\project\form-builder\node_modules\@delon\form\package.json)
```
不知道这个功能需要另外支持还是现有api可以实现只是我的方法不对?

注：如果直接使用nz-zorro组件或小部件，则还需自己构造schema，感觉和ng-alain重复了。

## What does the proposed API look like?
```
<sf-item [widget]="select" "schema"="schema" [ui]="ui" ></sf-item>
```
可能像这样，schema和ui的内容是sf的schema中某个properties的部分。

**Comment by rxxy** [comment]
看起来这2个使用场景还是非常有用的，非常感谢提供任何的帮助。

**Comment by cipchk** [comment]
若是对 `@delon/form` 进行深层次的定制，我个人比较建议可以直接复制整个源代码，进行生产，毕竟这里涉及的顺序问题，当前对这一部分是没有支持。

当然，上述中提到的未到找 `terminator.service` 错误，我没有办法进一步确认，需要提供更多使用代码。
