### ISSUE TITLE
@delon/cache's CacheService get via http doesn't support non-json data

### ISSUE THREAD

**Issue by xiaohuilam** [cipchk/ng-alain#2183]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-chb8le](https://stackblitz.com/edit/ng-alain-setup-chb8le)

### Steps to reproduce
    this.cacheService
      .get(`https://ca.quantumca.com.cn/test_text`)
      .subscribe(console.log);

To see if console triggers an error?

### What is expected?
cacheService load non-json data as usual

### What is actually happening?
cacheService triggered error.

| Environment | Info |
|---|---|
| ng-alain | 13.0.0 |
| Browser | Chrome 97.0.4692.71 (正式版本) (x86_64) |

**Comment by cipchk** [comment]
You can using `tryGet`, like this: 

```ts
const key = `https://ca.quantumca.com.cn/test_text`;
this.cacheService.tryGet(key, this.http.get(key, { responseType: 'text' })).subscribe(console.log);
```
