### ISSUE TITLE
sf数组小部件，`minItems ` 与条件表达式问题

### ISSUE THREAD

**Issue by Juicpt** [cipchk/ng-alain#2190]
### Reproduction link
[https://stackblitz.com/edit/angular-gj7eap](https://stackblitz.com/edit/angular-gj7eap)

### Steps to reproduce
添加两个以上对象数据，选上每一项的任务类型，然后删除一个对象数据

### What is expected?
期望提交按钮无法点击

### What is actually happening?
表单验证失效，提交按钮可点击

| Environment | Info |
|---|---|
| ng-alain | 13.1.0 |
| Browser | chrome 97.0.4692.99 |

**Comment by cipchk** [comment]
如果数据需要一个项，需要借助 `minItems: 1,`。

**Comment by Juicpt** [comment]
> 如果数据需要一个项，需要借助 `minItems: 1,`。

![image](https://user-images.githubusercontent.com/5248842/151541023-d302c771-c098-4d16-9fa1-368123dd5a3d.png)

https://stackblitz.com/edit/angular-gj7eap-6iqi3h

在加了 `minItems: 1,`情况下 还是会出现这个情况

**Comment by cipchk** [comment]
`visibleIf` 无法改变 `requrired`，导致其 Schema 不变被强制检验为必填项；可以使用 `if` 条件表达式：

```ts

schema: SFSchema = {
  properties: {
    list: {
      type: 'array',
      title: '任务流',
      minItems: 1,
      items: {
        type: 'object',
        properties: {
          type: {
            type: 'string',
            title: '任务类型',
            enum: [
              { label: '测试1', value: 'test1' },
              { label: '测试2', value: 'test2' },
            ],
            default: 'test1'
          },
          test1: {
            type: 'string',
            title: '测试1',
          },
          test2: {
            type: 'string',
            title: '测试2',
          },
        },
        required: ['type'],
        if: {
          properties: { type: { enum: [ 'test1' ] } }
        },
        then: {
          required: [ 'test1' ]
        },
        else: {
          required: [ 'test2' ]
        }
      },
    },
  },
};
```

**Comment by Juicpt** [comment]
> `visibleIf` 无法改变 `requrired`，导致其 Schema 不变被强制检验为必填项；可以使用 `if` 条件表达式：
> 
> ```ts
> schema: SFSchema = {
>   properties: {
>     list: {
>       type: 'array',
>       title: '任务流',
>       minItems: 1,
>       items: {
>         type: 'object',
>         properties: {
>           type: {
>             type: 'string',
>             title: '任务类型',
>             enum: [
>               { label: '测试1', value: 'test1' },
>               { label: '测试2', value: 'test2' },
>             ],
>             default: 'test1'
>           },
>           test1: {
>             type: 'string',
>             title: '测试1',
>           },
>           test2: {
>             type: 'string',
>             title: '测试2',
>           },
>         },
>         required: ['type'],
>         if: {
>           properties: { type: { enum: [ 'test1' ] } }
>         },
>         then: {
>           required: [ 'test1' ]
>         },
>         else: {
>           required: [ 'test2' ]
>         }
>       },
>     },
>   },
> };
> ```

我实际条件是不止两种情况，所以我还是需要直接用nz-form处理是吧。。。
