### ISSUE TITLE
delon/abc/xlsx 失效

### ISSUE THREAD

**Issue by YuTingKung** [cipchk/ng-alain#2191]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-eoqxuk](https://stackblitz.com/edit/ng-alain-setup-eoqxuk)

### Steps to reproduce
delon/abc/xlsx 內部所引用的外部 https://cdn.bootcdn.net/ajax/libs/xlsx/0.16.8/xlsx.full.min.js 無法獲取，導致xlsx失效

![image](https://user-images.githubusercontent.com/40377689/153369797-a5e412f7-fb83-41c6-88aa-d38848eed032.png)
![image](https://user-images.githubusercontent.com/40377689/153369863-1d0574bf-a938-4406-a281-7ec55e7dde14.png)

### What is expected?
xlsx 按鈕功能要可匯出

### What is actually happening?
按鈕無法反應

| Environment | Info |
|---|---|
| ng-alain | 12.0.3 |
| Browser | google chrome 版本 97.0.4692.71 (正式版本) (64 位元) |

**Comment by YuTingKung** [comment]
早上再度檢查，CDN已自行恢復。

![image](https://user-images.githubusercontent.com/40377689/153520977-ee594f0b-ea92-4de1-afcd-32467a3557d3.png)

**Comment by YuTingKung** [comment]
@cipchk 是否能夠讓 delon/abc/xlsx 的外部CDN轉成內部套件，避免外部CDN失效造成功能異常。

**Comment by cipchk** [comment]
@YuTingKung 有全局可配置项，参考：https://github.com/ng-alain/ng-alain/blob/master/src/app/global-config.module.ts#L14

**Comment by YuTingKung** [comment]
@cipchk 我認為全局可配置项無法解決我的問題，因為delon/abc/xlsx這個套件本身包含引用[外部的CDN](https://cdn.bootcdn.net/ajax/libs/xlsx/0.16.8/xlsx.full.min.js)，我需要的是在使用`import { XlsxService } from '@delon/abc/xlsx';`這個服務`export`的時候，Network不會呼叫外部的CDN，讓這個套件能自給自足。

**Comment by HsinM** [comment]
@YuTingKung You Can add relative url like
``` typescript
  ...},
  xlsx: {
    url: './assets/xlsx-0.18.7/xlsx.full.min.js'
  }
```
at https://github.com/ng-alain/ng-alain/blob/8eef48083a5b659ec8677fa90476212fdc672040/src/app/global-config.module.ts#L14-L22

**Comment by YuTingKung** [comment]
> @YuTingKung You Can add relative url like
> 
> ```ts
>   ...},
>   xlsx: {
>     url: './assets/xlsx-0.18.7/xlsx.full.min.js'
>   }
> ```
> 
> at
> 
> https://github.com/ng-alain/ng-alain/blob/8eef48083a5b659ec8677fa90476212fdc672040/src/app/global-config.module.ts#L14-L22

Thanks for your comment. It seems to be what I need.

**Comment by 66Sleeper** [comment]
> > @YuTingKung You Can add relative url like
> > ```ts
> >   ...},
> >   xlsx: {
> >     url: './assets/xlsx-0.18.7/xlsx.full.min.js'
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > at
> > https://github.com/ng-alain/ng-alain/blob/8eef48083a5b659ec8677fa90476212fdc672040/src/app/global-config.module.ts#L14-L22
> 
> Thanks for your comment. It since to be what I need.

我最近也遇到了这个问题，想问下xlsx.full.min.js你是在哪下载的呢

**Comment by YuTingKung** [comment]
@66Sleeper [xlsx.full.min.js](https://cdn.bootcdn.net/ajax/libs/xlsx/0.16.8/xlsx.full.min.js)

**Comment by 66Sleeper** [comment]
@YuTingKung 谢谢

**Comment by 66Sleeper** [comment]
@YuTingKung 你好，我想再问下下载到本地之后，和ng-alain文档的写法有不同嘛，我现在还是不生效，URL也配置了，
const alainConfig: AlainConfig = {
     ...
     xlsx: {
       url: './assets/xlsx.full.min.js'
}
}

**Comment by YuTingKung** [comment]
@66Sleeper 

![image](https://user-images.githubusercontent.com/40377689/169959232-53a4eaaa-0f12-4216-ab03-b3cb0d5f5978.png)

![image](https://user-images.githubusercontent.com/40377689/169959307-b5f75e8a-8883-44d4-9461-ab19e5c5b263.png)

![image](https://user-images.githubusercontent.com/40377689/169959413-9cbd53f3-ddbf-4a32-b021-e35b8666077b.png)

**Comment by 66Sleeper** [comment]
@YuTingKung 感谢，已经可以正常使用，文档过于简单，国内很少找到angular的问答
