### ISSUE TITLE
Route switchover in multiple languages 

### ISSUE THREAD

**Issue by YangYuHub** [cipchk/ng-alain#2196]
## What problem does this feature solve?
Currently I am unable to add language prefix in the URL. When I change language from dropdown the language is changed in page but url does not load with prefix. for example, i am switch to English, the URL should show www.test.com/en/some-page

I have checked the documentation but very minimal information is available.

## What does the proposed API look like?
I wish IT was easier to use ng-alain

https://medium.com/@oojhaajay/angular-i18n-content-translation-based-upon-url-68df087b73cd

like this ，It is best to integrate it into Ng-alain

**Comment by cipchk** [comment]
NG-ALAIN is not limited by which internationalization library you use, it may be built-in Angular, @ngx-translate, etc. No matter which library, you need to implement the `AlainI18NService` (https://github.com/ng-alain/delon/blob/master/packages/theme/src/services/i18n/i18n.ts#L10) interface for NG-ALAIN internal needs.

BTW, If you just want to reflect on the URL, you can customize a `canActivate` to get the URL internationalization code and feed it back to the corresponding service.

**I will also provide a unified solution similar to `AlainI18NGuard` in the future.**
