### ISSUE TITLE
[cli] Generate cannot use `-t` option but `--target` can

### ISSUE THREAD

**Issue by HsinM** [cipchk/ng-alain#2197]
### Reproduction link
[https://ng-alain.com/cli/generate/en](https://ng-alain.com/cli/generate/en)

### Steps to reproduce
Run:
ng g ng-alain:view view -m=sys -t=log

### What is expected?
Gen the new component.

### What is actually happening?
Cannot parse arguments. See below for the reasons.
    Argument -t could not be parsed using value "log".Valid type(s) is: boolean

| Environment | Info |
|---|---|
| ng-alain | 13.2.0 |
| Browser | N/A |

**Comment by HsinM** [comment]
Could it be that the following command line options conflict?
>`ng g ng-alain:view --help`

```
 --inline-template (-t)
    Include template inline in the component.ts file. By default, an external template file is created and referenced in the component.ts file.
 --target (-t)
    指定目标路径，支持 `bus/list` 写法 (Specifies relative path, could be set like `bus/list`.)
```

**Comment by cipchk** [comment]
Temporary solution: `ng g ng-alain:view --target=list`
