### ISSUE TITLE
表单校验问题

### ISSUE THREAD

**Issue by daiyang123456** [cipchk/ng-alain#2198]
重现地址：https://stackblitz.com/edit/angular-w9ndjh?file=src/app/app.component.ts
重现步骤：首次进入表单，表单无法提交
正常结果：首次进入表单，表单应该是可提交

**Comment by daiyang123456** [comment]
需要在packages/form/src/sf.component.ts 
230行改为【if (!this.liveValidate) this.validator({emitError: true, onlyRoot: true});】

**Comment by cipchk** [comment]
建议使用 `if` 条件表达式，例如：

```ts
{
    properties: {
      login_type: {
        type: 'string',
        title: '登录方式',
        enum: [
          { label: '手机', value: 'mobile' },
          { label: '账密', value: 'account' }
        ],
        default: 'mobile',
        ui: {
          widget: 'radio',
          styleType: 'button'
        }
      },
      mobile: {
        type: 'string'
      },
      code: {
        type: 'number'
      },
      name: {
        type: 'string'
      },
      pwd: {
        type: 'string',
        ui: {
          type: 'password'
        }
      }
    },
    required: ['login_type'],
    if: {
      properties: { login_type: { enum: ['mobile'] } }
    },
    then: {
      required: ['mobile', 'code']
    },
    else: {
      required: ['name', 'pwd']
    },
    ui: { debug: true }
  }
```

**Comment by cipchk** [comment]
不过关于 `visibleIf` 无法呈现 `required` 部分，这的确是一个需要改进的地方。

**Comment by KevinZhang19870314** [comment]
visibleIf 由外部条件触发没看到，只有针对某个字段改变触发而触发？
```
visibleIf: {
     [property name]: xxx
}
```
希望有：
```
visibleIf: boolean || () => boolean
```

**Comment by cipchk** [comment]
@KevinZhang19870314 若就你提供的DEMO当中来说，这里一开始无法提交是由于 `requried` 包含了 `name` ，则默认 `name` 又不需要呈现，所以就始终认为是错误的。你可以移除掉 `requried` 中的 `name` 值。

**Comment by KevinZhang19870314** [comment]
> @KevinZhang19870314 若就你提供的DEMO当中来说，这里一开始无法提交是由于 `requried` 包含了 `name` ，则默认 `name` 又不需要呈现，所以就始终认为是错误的。你可以移除掉 `requried` 中的 `name` 值。

@cipchk DEMO不是我提供的。。。我上面说的跟required没关系，我的意思是visibleIf可不可以由外部触发而不是由sf scheme里面的字段触发？比如说(手打的可能有语法错误)，我通过一个按钮控制age字段是否展示：
```
<div>
    <button [(ngModel)]="isShowAge">Toggle</button>
    <sf [scheme]="scheme"></sf>
</div>
<script>
scheme = {
    properties: {
        name: {
             type: 'string'
        },
       age: {
           type: 'number',
           ui: {
               visibleIf: () => return this.isShowAge
           }
       }
   }
}
</script>
```

**Comment by cipchk** [comment]
@KevinZhang19870314 可以尝试使用 `setVisible`:

```ts
const mobileProperty = this.sf.getProperty('/mobile');
mobileProperty?.setVisible(false);
mobileProperty?.widget?.detectChanges();
```

> 不过，非本 Issues 相关问题，请重新提交新的 Issues，以便更好的追踪。

**Comment by KevinZhang19870314** [comment]
> @KevinZhang19870314 可以尝试使用 `setVisible`:
> 
> ```ts
> const mobileProperty = this.sf.getProperty('/mobile');
> mobileProperty?.setVisible(false);
> mobileProperty?.widget?.detectChanges();
> ```
> 
> > 不过，非本 Issues 相关问题，请重新提交新的 Issues，以便更好的追踪。

@cipchk https://github.com/ng-alain/ng-alain/issues/2200
