### ISSUE TITLE
Delon表单中的ui.visibleIf增加由外部触发条件控制字段展示与否

### ISSUE THREAD

**Issue by KevinZhang19870314** [cipchk/ng-alain#2200]
## What problem does this feature solve?
目前visibleIf只能由sf中的某一个property控制其是否展示，希望可以由外部控制，比如说(手打的可能有语法错误)，我通过一个按钮控制age字段是否展示：
```
<div>
    <button [(ngModel)]="isShowAge">Toggle</button>
    <sf [scheme]="scheme"></sf>
</div>
<script>
scheme = {
    properties: {
        name: {
             type: 'string'
        },
       age: {
           type: 'number',
           ui: {
               visibleIf: () => return this.isShowAge
           }
       }
   }
}
</script>
```

## What does the proposed API look like?
visibleIf: boolean || () => boolean

**Comment by KevinZhang19870314** [comment]
当然这个可以有一个workaround如你再[issue](https://github.com/ng-alain/ng-alain/issues/2198#issuecomment-1062734738)中提到，但是仍希望能增加此功能。

**Comment by cipchk** [comment]
事实上，不管是否 `visibleIf` 支持 `function` 的形式，最终想要由外部产生生效，依然需要获取相应的目标（可能是修改某个元素值或`reset`），修改后重新触发表单的校验。本质上同在 https://github.com/ng-alain/ng-alain/issues/2198#issuecomment-1060212792 一样类似的处理。因此，我不认为增加 `function` 的支持会改变得更加友好；依然建议使用 `setVisible`。在新的版本中我会给 `setVisible` 返回 `this`，所以在新的版本当中会更优雅的调用方式为：

```ts
this.sf.getProperty('/mobile')?.setVisible(status).widget.detectChanges();
```

**Comment by KevinZhang19870314** [comment]
> 事实上，不管是否 `visibleIf` 支持 `function` 的形式，最终想要由外部产生生效，依然需要获取相应的目标（可能是修改某个元素值或`reset`），修改后重新触发表单的校验。本质上同在 [#2198 (comment)](https://github.com/ng-alain/ng-alain/issues/2198#issuecomment-1060212792) 一样类似的处理。因此，我不认为增加 `function` 的支持会改变得更加友好；依然建议使用 `setVisible`。在新的版本中我会给 `setVisible` 返回 `this`，所以在新的版本当中会更优雅的调用方式为：
> 
> ```ts
> this.sf.getProperty('/mobile')?.setVisible(status).widget.detectChanges();
> ```

@cipchk 增加func的形式好处是我不需要再外部写代码来包装这个额外的逻辑了，类似于在上面的例子中，在build scheme的时候就处理好了，外部绑定的ngModel值改变，这里的func会自动返回相应的值给这个widget内部的visibleIf的绑定。
当然这个在我的项目封装里面觉得方便一些，你说的也有道理，如果觉得不需要就不加了。

![image](https://user-images.githubusercontent.com/13794286/157569551-301429fe-06ad-461c-9d85-b3f4a9837ae8.png)
