### ISSUE TITLE
sf的checkbox 小部件 使用  asyncData + default ，设置val的时候，会合并val和default

### ISSUE THREAD

**Issue by asher-fire** [cipchk/ng-alain#2202]
### Reproduction link
[https://stackblitz.com/edit/angular-rxx4q9?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-rxx4q9?file=src/app/app.component.ts)

### Steps to reproduce
1. 点击提交按钮即可以
2.  submit函数里面有多种设置值的方法，均为达到预期效果

### What is expected?
达到checkbox 小部件使用 enum   + default 一样正常的结果，希望是点击按钮修改值达到如下效果：
![image](https://user-images.githubusercontent.com/16936239/157661898-18e7d5ce-91d4-4033-91f5-89ededc7c48e.png)

### What is actually happening?
sf的checkbox 小部件 使用  asyncData  + default ，设置val的时候，会合并val和default
![image](https://user-images.githubusercontent.com/16936239/157662227-c86a2251-bf52-4b4c-9be9-295f3187cf28.png)

| Environment | Info |
|---|---|
| ng-alain | 13.2.1 |
| Browser | google 94.0.4606.61 |

**Comment by asher-fire** [comment]
多种设置值的方法 

// ① 
    this.formData2 = { async: 'F' };
// ② 
    this.sf.setValue('/async', ['F']);
// ③ 
    const statusProperty = this.sf.getProperty('/async');
    statusProperty.widget.reset(['F']);

**Comment by cipchk** [comment]
从示例上看，并非 `formData` 会合并的假象是数据污染，可以试着修正两处效果：

```diff
- asyncData = new BehaviorSubject([ {}, {} , {} ]);
+ asyncData = new BehaviorSubject([]);

- asyncData: () => this.asyncData,
+ asyncData: () => this.asyncData.asObservable().pipe(map(() => deepCopy(this.arr)))
```

应该就可以看出效果了。

换言之就是小部件对 `checked` 参数的变化，实际也影响到了外部的数据源。当然这是你写的 `asynData` 的问题，而为什么同样 `enum` 不会呢？因为这是 JSON Schema 标准之一，在做 Schema 处理时始终都会进行一次深度复制。
