### ISSUE TITLE
自定义模板时，cli生成list时，不生成组件，但更新了模块。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2208]
### Reproduction link
[https://github.com/ng-alain/ng-alain/tree/master/_cli-tpl/test/__path__/__name%40dasherize%40if-flat__](https://github.com/ng-alain/ng-alain/tree/master/_cli-tpl/test/__path__/__name%40dasherize%40if-flat__)

### Steps to reproduce
使用`ng g ng-alain:list sms -m=services`生成组件，不使用自定义时可以有效生成。自定义后，不生成组件，但更新模块导入。
我直接拿test目录改为_list也同样不可以生成。
文件拿[delon中的list模板](https://github.com/ng-alain/delon/blob/master/schematics/list/files/__path__/__name%40dasherize%40if-flat__/__name%40dasherize__.component.html.template)直接复制过来。也是同样的问题。
路径无误，`_list/__path__/__name@dasherize@if-flat__/__name@dasherize_*`
### What is expected?
可以使用自定义模板

### What is actually happening?
使用后不能正常生成组件，但在模型中却导出了这个不存在的组件。

| Environment | Info |
|---|---|
| ng-alain | 13.2.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
我无法重现这种情况，以 NG-ALAIN 源代码的环境下，我的完整路径：

```
/Users/cipchk/Desktop/work/ng-alain/_cli-tpl/_list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
```

命令：

```base
ng g ng-alain:list sms -m=delon
```

一切正常。

**Comment by xingkoo** [comment]
可能是我的用法有问题。在根目录下使用可以正常生成。切换到子目录下无法生成。（默认的可以生成）
（主要是分了好多次子模块，在根目录下指定孙子父辈模块下生成。）
![image](https://user-images.githubusercontent.com/2936579/158993403-8d21c5de-d488-461d-b42a-29d0fead8c36.png)

![image](https://user-images.githubusercontent.com/2936579/158993586-4d694079-ad3d-4319-b22f-53cdd629e0de.png)
