### ISSUE TITLE
No value accessor for form control with name: 'xxx'

### ISSUE THREAD

**Issue by tuphampro** [cipchk/ng-alain#2213]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-sqjaeg?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-sqjaeg?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Error using form

### What is expected?
Fix bug

### What is actually happening?
Fix bug

| Environment | Info |
|---|---|
| ng-alain | 13.4.0 |
| Browser | Safari |

<img width="1280" alt="Screen Shot 2022-03-21 at 22 15 26" src="https://user-images.githubusercontent.com/19162524/159296564-2dd12e64-8e36-45d6-87c5-494d59a828fb.png">

**Comment by cipchk** [comment]
You provided the reproduction DEMO link is woking:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/2987467/159402523-1bda530d-1416-4413-8fe2-1e32b0144bd1.png">

BTW, According to the `No value accessor for form control with name: 'x'` error message, it should be that you didn't use `formControlName` correctly.

**Comment by tuphampro** [comment]
Using the latest version will have the same problem.

![ảnh](https://user-images.githubusercontent.com/19162524/159413738-985a2502-e276-4f76-aac9-a9363677b746.png)

**Comment by tuphampro** [comment]
you can follow these steps **https://ng-alain.com/docs/getting-started/en#CLIRecommend** and then add the form

**Comment by cipchk** [comment]
Can provide a reproducible stackblitz DEMO, I can work in my env.

**Comment by tuphampro** [comment]
you can follow these steps https://ng-alain.com/docs/getting-started/en#CLIRecommend and then [add the form ](https://ng.ant.design/components/form/en#components-form-demo-time-related-controls)

**Comment by cipchk** [comment]
Sorry, I still can't reproduce. Pls provide via stackblitz.
