### ISSUE TITLE
能否修正一些bug后，delon异步发行一个小版本？

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2214]
## What problem does this feature solve?
比如前面提到的一个cli生成list的bug，delon已经完成修复，但是未发布版本，就一直不能使用这个功能。
一些比较小挂件之类的可以临时自定义一个替换使用，但是像cli这种基础功能，基本没有办法处理。

## What does the proposed API look like?
修正bug可发布个小版本delon，如果有需要，用户自己手动更新。
只有标准的版本发布，才会和ng-alain同步进行升级。

**Comment by cipchk** [comment]
每周五会固定发布一次小版本。
