### ISSUE TITLE
三级模块下的组件不能获取到header

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2215]
### Reproduction link
使用同样的page-header，得到不同的结果。
```
<page-header [action]="phActionTpl">
  <ng-template #phActionTpl>
    <button (click)="add()" nz-button nzType="primary">新建</button>
  </ng-template>
</page-header>
```
![image](https://user-images.githubusercontent.com/2936579/160209041-243d29e5-dbb4-42ca-ae4c-52df63560c13.png)

![image](https://user-images.githubusercontent.com/2936579/160209012-4ab7acbb-efbb-4cf6-ad26-2269923eac3a.png)

### Steps to reproduce
创建adminModule，下面创建databaseModule，下面再创建reportModule，该模块下有ListComponent。
此时不显示Header Title。
如果是在databaseModule下的组件，则可以正常获取到header Title.
我手工指定title属性时，可以显示标题。相应的，面包屑很有可能也不能正常获取。

### What is expected?
可以支持多级模块。

### What is actually happening?
当前应该是不能获取到3级模块的。

| Environment | Info |
|---|---|
| ng-alain | 13.4.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
能否获取到标题，是由 `MenuService` 中的数据是否有相同的 URL 与路由相匹配为基准。

**Comment by xingkoo** [comment]
确实是这样的原因，/admin/1/database/report/list && /admin/1/database/report 的差别。同样能访问到该页面，但后面的list被省略后就不能匹配上了。感谢提醒。
