### ISSUE TITLE
增加对元素对象的移除支持

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2216]
## What problem does this feature solve?
某些场景下，需要移除对象中的元素。比如SF的结构定义全部属性，在不同的场景，仅使用其中部分属性。我就需要引入sfs结构定义时，提交移除部分属性。

## What does the proposed API look like?
可以移除对象元素，且支持多层级的移除。
增强 https://ng-alain.com/util/other/zh 对数组的支持。

**Comment by cipchk** [comment]
这一点内部的 `visibleIf` 已经做了很干净，但无法保证绝对的干净，例如像编辑表单可能会有额外的属性参数。就目前而，如果对后端请求的数据有非常严格的管控，那么也只能手动修复，因为 `sf` 的确无法百分之百的保证这是一个你认为的干净结果。

> 关于 Utils 数组的支持是指什么意思？像：https://ng-alain.com/util/array/zh  若有相应需求建议发表新的 Issues 单独阐述。

**Comment by xingkoo** [comment]
直接在引入结构前就对结构数组中不该存在的移除掉，是不是更直接一点。当然，使用if，通过场景的方式来决定是否显示，可能也会是种体验。但是需要额外增加属性来处理。确实没有引用前就把数据清洗干净直观。
除了SFS，其他地方也有可能会用到移除对象属性的情况。这是个单独的工具。

**Comment by cipchk** [comment]
可以利用 [lodash.omit](https://www.npmjs.com/package/lodash.omit).
