### ISSUE TITLE
能否增加对菜单是否展开的控制开关

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2218]
## What problem does this feature solve?
菜单列表默认都是合上的，个别菜单想让默认展看。翻看了一下代码，确实没有找到相关的控制参数。

## What does the proposed API look like?
某些菜单可以默认展开。

**Comment by cipchk** [comment]
```ts
SettingsService.setLayout('collapsed', status);
```

**Comment by xingkoo** [comment]
我看到文档，
`SettingsService.setLayout('collapsed', status);` 
这个应该是控制整个菜单的展开效果的吧？
如果我想控制个别菜单，如下面代码中的`collapsed: true,`来控制当前菜单是否展开，目前似乎是可以实现的吗？
```

      menu.push({
        text: i.title,
        link: i.code.replace('{id}', id),
        icon: i.icon || 'anticon-dashboard',
        nodeId: i.nodeId,
        collapsed: true,
        topId: i.topId,
        acl: { ability: [Number(i.nodeId)] }
      });
```
