### ISSUE TITLE
能否对Menu的Item增加collapsed属性支持

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2228]
## What problem does this feature solve?
我看到文档，
SettingsService.setLayout('collapsed', status);
这个应该是控制整个菜单的展开效果.
如果想控制个别菜单的展开，如下面代码中的collapsed: true,来控制当前菜单是否展开，目前似乎不能实现。
能否增加这个功能的支持。
```
      menu.push({
        text: i.title,
        link: i.code.replace('{id}', id),
        icon: i.icon || 'anticon-dashboard',
        nodeId: i.nodeId,
        collapsed: true,
        topId: i.topId,
        acl: { ability: [Number(i.nodeId)] }
      });
```

## What does the proposed API look like?
对Menu的Item增加collapsed属性。

**Comment by cipchk** [comment]
看不下去了，有必要重构一下 `MenuService` 不合理的接口。

>  而目前能解决的问题，可以是 `setItem('key', { _open: false | true })` 不过需要开启 `openStrictly: true`。
