### ISSUE TITLE
ng g ng-alain:sta 生成的queryParams名称过长，生成的dto的属性为大写

### ISSUE THREAD

**Issue by tilark** [cipchk/ng-alain#2236]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce
```
  /**
   * @request GET:/api/services/app/ProductCategory/GetAll
   */
  servicesAppProductCategoryGetAllList(
    req?: ProductCategoryServicesAppProductCategoryGetAllListRequest,
    options?: STAHttpOptions
  ): Observable<ProductCategoryDtoPagedResultDto> {
    return this.request('GET', `/api/services/app/ProductCategory/GetAll`, {
      params: req,
      ...options
    });
  }

export interface ProductCategoryServicesAppProductCategoryGetAllListRequest {
  Name?: string;
  Sorting?: string;
  SkipCount?: number;
  MaxResultCount?: number;
}
```

### What is expected?
1、生成的servicesAppProductCategoryGetAllList中的queryParams： ProductCategoryServicesAppProductCategoryGetAllListRequest，名称长，希望能缩短，便于阅读。
2、生成的dto中的属性是大写，建议改成首字母小写

### What is actually happening?
none

| Environment | Info |
|---|---|
| ng-alain | 13.4.2 |
| Browser | chrome 100 |

**Comment by cipchk** [comment]
关于名称的生成方式，建议尽可能的输出 `operationId`。
