### ISSUE TITLE
引入micro-app报错

### ISSUE THREAD

**Issue by vurtnr** [cipchk/ng-alain#2237]
### Reproduction link
[https://codesandbox.io/s/sad-swartz-6vqm8s?file=/src/app/app.module.ts](https://codesandbox.io/s/sad-swartz-6vqm8s?file=/src/app/app.module.ts)

### Steps to reproduce
启动

### What is expected?
micro-app 标签识别并跳转微前端页面

### What is actually happening?
Error: src/app/routes/subapp1/subapp1.component.html:1:1 - error NG8001: 'micro-app' is not a known element:
1. If 'micro-app' is an Angular component, then verify that it is part of this module.
2. If 'micro-app' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

| Environment | Info |
|---|---|
| ng-alain | 12.4.2 |
| Browser | brave |

**Comment by vurtnr** [comment]
PS：未安装ng-alain的angularcli12版本项目没有问题，一切正常。ng add ng-alian@12.4.2之后 引入相同代码配置，则报上述错误

**Comment by cipchk** [comment]
> If 'micro-app' is an Angular component, then verify that it is part of this module.

这人意思就是说所在的模块缺少 `micro-app` 模块的导入。

**Comment by vurtnr** [comment]
> > If 'micro-app' is an Angular component, then verify that it is part of this module.
> 
> 这人意思就是说所在的模块缺少 `micro-app` 模块的导入。

按照micro-app官方angular的例子导入了。appmodule里通过配置@NgModule（{schemas: [CUSTOM_ELEMENTS_SCHEMA]}）的方式在未引入ng-alain的项目中是可以找到micro-app的，所以想问问是不是哪里需要配置还是如何？

**Comment by cipchk** [comment]
`CUSTOM_ELEMENTS_SCHEMA` 只是表示允许模块包含自定元素的内容，假如你的 `micro-app`  组件所在的模块没有在合适的位置导入，或者说使用 `createCustomElement` 创建一个 `micro-app` 的组件，也是依然会错误的。当然如果你不想要这么错误 ，则可以导入  `NO_ERRORS_SCHEMA`。

**Comment by vurtnr** [comment]
> `CUSTOM_ELEMENTS_SCHEMA` 只是表示允许模块包含自定元素的内容，假如你的 `micro-app` 组件所在的模块没有在合适的位置导入，或者说使用 `createCustomElement` 创建一个 `micro-app` 的组件，也是依然会错误的。当然如果你不想要这么错误 ，则可以导入 `NO_ERRORS_SCHEMA`。

您说的这个解决方案不起效，其实很简单，为什么空白项目同样的配置没问题而add ng-alian之后出现这样的问题。

**Comment by vurtnr** [comment]
@cipchk 您好 能否看下我附上的link。官方是否还有其他的解决方案，瑞斯拜~

**Comment by cipchk** [comment]
我没有试过 micro-app，但看起来你并没有在 NgModule 中注册 `Subapp1Component` 组件。

**Comment by vurtnr** [comment]
@cipchk 已经解决 不好意思  因为刚接触angular，Subapp1Component组件是我从其他demo中复制过来做测试的，忘记在AppModule中注册 导致了这个问题。
