### ISSUE TITLE
STColumn buttons数量不能够自由定义

### ISSUE THREAD

**Issue by pjxgithub** [cipchk/ng-alain#2239]
## What problem does this feature solve?
操作列能够固定宽度，增加操作体验
场景：单据列表，不同的状态 操作的按钮数量不一样 
ID               状态              操作
1                 草稿              编辑 删除 审核 择日审核
2                 审核              作废 完成
3                 作废              无
假设 有一个草稿的  其他的状态都没有权限操作 那么 就需要占用到 4个按钮的宽度 其他状态的数据都是空白的

调整成为 只需要固定占用两个按钮的宽度
1                 草稿              编辑  更多（删除 审核 择日审核）
2                 审核              作废 完成
3                 作废              无

## What does the proposed API look like?
STColumn的buttons是属性 调整成为 属性或者方法，传入当前记录行 返回STColumnButton<T>[]即可

**Comment by ococl** [comment]
也遇到了这个问题，有时候会留个空框在那里，看起来挺尬的。
如果有方便的途径能动态调整操作列的宽度以及是否显示就好了。

现在我用的是`st.resetColumns()`，有些那个不太爽。
