### ISSUE TITLE
想确认一下现在是否有异步处理动态表单错误提示信息？

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2240]
## What problem does this feature solve?
比如身份证号，后台要求唯一，提交后，后台检测不唯一，反馈错误提示，如何在前台表单上展示出来？

## What does the proposed API look like?
可以通过对后台返回的错误提示，通过某个接口，在表单中体现出来。

**Comment by cipchk** [comment]
可以参考 [异步校验](https://ng-alain.com/form/error/zh?#%E5%BC%82%E6%AD%A5%E6%A0%A1%E9%AA%8C)，不过里有一个弊端，这类远程请求校验会频繁性的触发，需要自行处理缓存。例如：

```ts
schema: SFSchema = {
  properties: {
    name: {
      type: 'string',
      ui: {
        showRequired: true,
        validator: (value: string) => of(true).pipe(
          delay(1000),
          map(res => value.length !== 18 ? [ { keyword: 'required', message: '身份证不正确' } ] : [])
        )
      }
    }
  }
};
```

**Comment by xingkoo** [comment]
这种异步处理方式适合使用单个属性。
我期望的是能够有一个接口，可以简易的对后端返回的错误在表单上提示出来。
不知道是否可以实现，或者增加一个这样的接口。
个人认为这种场景还是比较常见的。

如果是多个属性并列唯一或其他相对复杂一些的处理过程，
大概是请求后端后，后端返回某某项和某类似这样的请求：
```
http.get('url').subscript(res=>{
  msg('保存成功');
  location.href='...';
},error=>{
    // 使表单对应属性显示出错误信息
});
```
返回错误信息时，使表单对应属性显示错误提示
```
{
  status: 'error',
  msg:'保存数据时发生错误',
  data:{
    title: '超出长度',
    name: '名称已被使用',
  }
}
```

**Comment by xingkoo** [comment]
@cipchk 可能需要麻烦你看一下上面说的是否可以实现。

**Comment by cipchk** [comment]
目前的确没有可被调用的接口，不过可以利用 `setErrors` 方法来处理，例如：

```ts
const name = this.sf.getProperty('/name');
const errs: ErrorData[] = [{ keyword: 'required' }];
name!['setErrors'](errs);
```

我会把 `setErrors` 调整为 `public`。
