### ISSUE TITLE
sf的标题长度超过后会显示...，需要支持鼠标移动到标题上可以通过tips显示完整标题信息

### ISSUE THREAD

**Issue by aLoNeIT** [cipchk/ng-alain#2255]
## What problem does this feature solve?
解决了在有限空间内标题不完整显示的问题。

## What does the proposed API look like?
schema.ui.key.titleTips

**Comment by aLoNeIT** [comment]
如图所示
![sf_title](https://user-images.githubusercontent.com/22443713/171617647-5481a7c0-3b2b-470a-ac94-14d8e852f39b.png)

**Comment by cipchk** [comment]
不加 `title` 的主要原因是，当所有元素都带有 title 时鼠标的触碰很容易产生包含不需要产生的的悬停状态。你可以简化标签并使用 `optionalHelp` 进一步说明；或者将三列变成二列。或使用 `spanLabelFixed` 来调整 Label 的宽度。
