### ISSUE TITLE
自定义菜单

### ISSUE THREAD

**Issue by lyy6702** [cipchk/ng-alain#2258]
## What problem does this feature solve?
不再是传统菜单样式，个性化的菜单

## What does the proposed API look like?
希望菜单样式能自定义，但路由这方面的还保留

**Comment by cipchk** [comment]
使用 `nav` 属性即可自定义菜单， https://ng-alain.com/theme/layout-default/zh?#layout-default

**Comment by lyy6702** [comment]
有实例吗？@alain-default-aside-scrollbar-thumb-color  
@alain-default-aside-bg

怎么用？

 <ng-template #navTpl>
        <layout-default-nav 
        
        class="d-block py-lg"></layout-default-nav>
      </ng-template>
在里面写吗？  layout-default-nav  我想用我自定义的组件 ，因为 现在的菜单是上下层结构，我要改成一级菜单只有图标，二级菜单在一级的左边， 

一级菜单图标 
                            1.1  订单  （当点击二级菜单图标后，2.2 报表）
                            1.2  列表  （当点击二级菜单图标后，2.2 商品）
二级菜单图标

**Comment by lyy6702** [comment]
一级菜单  

                        1. 订单（当点击二级菜单图标后，2.2 报表）
                        2. 列表（当点击二级菜单图标后，2.2 商品）
 二级菜单
