### ISSUE TITLE
setps组件迷你模式下，进程状态的进度条显示异常。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2264]
### Reproduction link
[https://github.com/ng-alain](https://github.com/ng-alain)

### Steps to reproduce
![截屏2022-06-14 21 52 59](https://user-images.githubusercontent.com/2936579/173594377-7782bea4-b014-4891-900c-f909ddd04593.png)
https://ng-alain-setup-gef5cp.stackblitz.io

### What is expected?
正常展示

### What is actually happening?
显示错误

| Environment | Info |
|---|---|
| ng-alain | 13.5.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
这应该是 ng-zorro-antd 组件引起的，见 https://github.com/NG-ZORRO/ng-zorro-antd/issues/7513
