### ISSUE TITLE
st: 提取st中与视图无关，仅与获取数据有关的行为，封装成一个新的数据源组件

### ISSUE THREAD

**Issue by zbrongyaozb** [cipchk/ng-alain#2267]
## What problem does this feature solve?
https://stackblitz.com/edit/ng-alain-setup-qgojxe?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdata-source%2Fdata-source.component.html

通过st的data属性，可以方便快速的通过url来获取接口，并且支持分页。
但是视图渲染是能是表格。有些时候，希望自定义视图，但是又希望能用上st的data功能，来自动获取数据。

所以现在希望可以提供一个基础组件，它只负责提供一些数据相关的操作，比如包括导出重置删除等st原本就支持的功能。
在上面的例子中，我把st复制了一份，然后稍微改了改，模板里加了个分页，class里加了泛型。然后使用这个组件的时候，传入和st一样的属性，就可以拿到数据自行渲染了。

## What does the proposed API look like?
希望如下：
1.新组件应当拥有所有st与视图渲染无关的方法与属性。
2.新组件可以拥有一些多余的属性和方法，这些方法可能是为了保障其它一些必要方法的正常运行。
3.最好st是继承自这个新组件的。
4.关于全局配置，可以独立一套也可和st共用一套，理论上影响不大。

另外这个功能不是太紧急，毕竟copy的也能用，但是还是希望可以用上官方支持的版本~

**Comment by wyq-L** [comment]
很简单 自定义一列就行了实例代码如下：
`Columns: STColumn[] = [{ title: '自定义', renderTitle: 'customTitle', render: 'custom' }];`

**Comment by zbrongyaozb** [comment]
> 很简单 自定义一列就行了实例代码如下： `Columns: STColumn[] = [{ title: '自定义', renderTitle: 'customTitle', render: 'custom' }];`

不是要简单的自定义列，具体可以看看stackblitz里的demo里下方的卡片列表。

**Comment by xingkoo** [comment]
之前我也提过一个类似的问题，后来自己选择通过单列自定义的方式来变相实现，关闭了那个问题。
但是这确实是个好问题，真的有这种需求。
