### ISSUE TITLE
动态表单日期时间组件同时使用type和format时处理结果不正确。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2270]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-wfbqym?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-wfbqym?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击提交按钮，第一个值仅获取到了年。第二个值是预期中的时间辍

### What is expected?
修复该问题。

### What is actually happening?
出现了bug

| Environment | Info |
|---|---|
| ng-alain | 13.5.1 |
| Browser | chrome |

**Comment by xingkoo** [comment]
![截屏2022-07-03 21 11 51](https://user-images.githubusercontent.com/2936579/177041346-97dc3b8b-0479-4da5-9f3c-a122d2dfd6b4.png)

**Comment by cipchk** [comment]
时间值本身是一个 `string` 类型，所以起效时间应该设置为 `type: 'string'`。
