### ISSUE TITLE
ST column format string to barcode picture 

### ISSUE THREAD

**Issue by YuTingKung** [cipchk/ng-alain#2278]
## What problem does this feature solve?
ST表格，從伺服器端接收到字串後，可以從客戶端透過[套件](https://www.npmjs.com/package/bardcode)或其他function轉換成barcode(Code 39)圖片，顯示在表格上，[展示](https://barcode.tec-it.com/zh/Code39)，讓使用者可以用手持裝置掃描網頁表格上的條碼。

![](https://i.imgur.com/i5KbR61.png)

## What does the proposed API look like?
```
columns: STColumn[] = [
    {
        title: 'barcode',
        index: 'barcode_string',
        type: 'barcode',
        barcode_formats: 'Code 39'
    }
]
```

**Comment by cipchk** [comment]
ST 支持 widget 的写法，可以自行添加，参考：https://ng-alain.com/components/st/en?#components-st-widget
