### ISSUE TITLE
Incorrect style of `Se` component when the form is not validated

### ISSUE THREAD

**Issue by kevindaizj** [cipchk/ng-alain#2279]
### Reproduction link
[https://github.com/kevindaizj/ng-alain-form-error-style](https://github.com/kevindaizj/ng-alain-form-error-style)

### Steps to reproduce
1. add ng-alain
2. see different behavior between `se` and `nz-form-item` in [login.component.html](https://github.com/kevindaizj/ng-alain-form-error-style/blob/master/src/app/routes/passport/login/login.component.html)
3. submit the form.

#### `se` component: *NO* red borders appear, which is incorrect.
```
  <!-- NO red borders -->
  <se error="Error!">
    <input nz-input formControlName="userName" />
  </se>

```

####  compare with `nz-form-item`:  The red borders appear.
```
  <nz-form-item>
    <nz-form-control nzErrorTip="Error!">
      <input nz-input formControlName="userName" />
    </nz-form-control>
  </nz-form-item>
```

### What is expected?
red borders around input appear when control is not validated

### What is actually happening?
no red border appear

| Environment | Info |
|---|---|
| ng-alain | 13.5.2 |
| Browser | All |

**Comment by cipchk** [comment]
Simple reproduce: https://stackblitz.com/edit/angular-umdbvr?file=src%2Fapp%2Fapp.component.ts
