### ISSUE TITLE
请教一个问题，使用抽屉组件时，能否人工标记决定关闭时是否执行回调。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2280]
## What problem does this feature solve?
假设我在`页面A`中，使用`Drawer`组件打开了一个`页面B`，在`B页面`中，使用`Modal`弹出一个`页面C`。

当我在`页面C`中做出一些修改操作时，一般情况下，可以**主动**通过`res.close(data)`关闭，并触发`页面B`的中的model回调。

而此时，点击`页面B`的蒙板或者点击关闭按钮时，并不会触发`页面A`的回调（当然，exact=false时除外。）。

我如何可以通过在关闭`页面C`时，在`页面B`中做一些标识，以改变（非主动使用`close()`方法）时，能够触发`页面A`的回调。

## What does the proposed API look like?
如上。

**Comment by cipchk** [comment]
事实上，这种带有深度的，我个人更建议新建一个 Service 并使用 `Subject` 用于消息传递。

**Comment by xingkoo** [comment]
在一些更复杂的场景中确实是使用订阅事件的方式来做变更。
而事件订阅用的过多，可能需要专门管理订阅列表，使用文档来记录下来，以便维护更新，也导致使用起来会比较复杂。

我想的是，能否通过自定义点击蒙板或者关闭按钮，来更简单的实现一些父子交互。
主要是有些场景，子组件做一些变更后，并未第一时间关闭子组件，如果能简单的标识一下，关闭的时候，强制触发一下父组件，就能更加简单了，也不需要做文档专门记录此事。
当然，如果实现也很麻烦，那么事件订阅可能就是最好的选择了。
麻烦卡色大佬帮忙评估一下是否值得做这么一个封装。
