### ISSUE TITLE
se上组件不正确的展示

### ISSUE THREAD

**Issue by Ludidi** [cipchk/ng-alain#2281]
### Reproduction link
[https://stackblitz.com/edit/angular-wojcdn?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-wojcdn?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
链接打开即可看到，指定默认的required为false的时候，必填标识符显示错误

### What is expected?
必填标识符显示正常

### What is actually happening?
必填标识符显示错

| Environment | Info |
|---|---|
| ng-alain | 13.5.2 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 |

**Comment by cipchk** [comment]
正确的应该是 `[attr.required]`
