### ISSUE TITLE
ng-alaian select tree-select 样式不正确

### ISSUE THREAD

**Issue by 943885179** [cipchk/ng-alain#2283]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
正常看官方文档就有问题了，select下拉的，设置width都无效

### What is expected?
设置width正常生效（12是生效的），默认的长度可以设置，动态扩展

### What is actually happening?
下拉显示很有问题

| Environment | Info |
|---|---|
| ng-alain | 13.5.2 |
| Browser | chrome 91 |

**Comment by cipchk** [comment]
@943885179 若是官网组件的问题，麻烦至 https://github.com/NG-ZORRO/ng-zorro-antd
