### ISSUE TITLE
表格列格式化增强。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2294]
## What problem does this feature solve?
很多表格表需要用到简单的格式化，如
```
format: (item: STData, col: STColumn, index: number) => {
   return item['status'] ? '启用' : '禁用';
}
```
这种情况非常常见，能否直接增加一个
```
status:{validText: '启用', invalidText:'禁用', otherText?:'其他'}
```
或者
```
status:['启用', '禁用', '其他'?}
```
这样的方式，来简化format。

## What does the proposed API look like?
如上所述，增加简化列格式化的功能。

**Comment by cipchk** [comment]
`badge` 或 `tag` 都可以完成。

> 一般而言，可以自定义一个方法，统一生成 `badge` 的 Column。
