### ISSUE TITLE
Dark Theme 背景太黑，字体太白，有点刺眼

### ISSUE THREAD

**Issue by forecho** [cipchk/ng-alain#2297]
## What problem does this feature solve?
体验更好的 Dark Theme 

## What does the proposed API look like?
https://beta-pro.ant.design/index-cn Dark Theme 可参考

**Comment by cipchk** [comment]
Dark 主题是以 ANTD 的主题色为基准，事实上你是你可以修改的，一般只需要在 theme.less 下直接覆盖新的，例如背景色 [@body-background](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/dark.less#L164):

```less
@body-background: #f50;
```
