### ISSUE TITLE
st-filter 使用showOPArea:false时，提供方法关闭下拉菜单

### ISSUE THREAD

**Issue by zbrongyaozb** [cipchk/ng-alain#2299]
## What problem does this feature solve?
自定义了些复杂的过滤器，内部有确认和取消按钮，所以使用了STColumnFilter的showOPArea属性，隐藏了默认的操作按钮。
但是触发查询后，无法自动关闭过滤器的下拉菜单。
现在希望可以提供方法或属性，可以控制过滤菜单的关闭

## What does the proposed API look like?
STColumnFilter里提供一个visible，STFilterComponent优先使用STColumnFilter里的visible
或者其它方式也可

**Comment by zbrongyaozb** [comment]
大佬给力，现在还有有另一个需求，不知道有没有必要实现，这里先讨论下。

就是STColumnFilter的custom目前只支持传入模板，导致所有的页面上都会有固定的样板代码，比如：
```
<ng-template #filter let-f let-col="col">
  <column-filter-st [f]="f" [col]="col"></column-filter-st>
</ng-template>
```

再然后不方便的地方就是需要在OnInit初始化方法里才能设置custom的模板，而我这边stColumn是和组件脱离的，放在了service里，主要是为了其它页面复用column。
这就导致主体的stColumn定义在service里，然后filter模板的设置要在页面组件的初始化方法里。
当然我的st本身是挂了层指令的，这样把设置filter模板的工作转移到指令里自动执行应该也是可行的。

总得来说这不是个必需的需求，实现难度大就可以不考虑，当然有的话，代码也可以简洁灵活不少。

**Comment by cipchk** [comment]
首先的确可以实现，实现类似 Widget 的方式，但是这又使得 `st` 越来越重，所以还是不会考虑的。

不过若是单纯考虑关注分离原则，事实上，并不需要 `st` 来完成，大可自己内部实现，将需要自定义 Filter 的 `ng-template` 放进一个 Compoen 里面，同时再配合一个 Service，进一步组装。

设计模板除了分离，也有组合。

**Comment by zbrongyaozb** [comment]
模板放到组件里，再塞到service里，这个确实也试过。主要问题就是依赖注入会比较麻烦，我现在每个增删改查的页面都是有独立的一套service，当我把模板放到页面之外的某个地方，虽然是可以拿到模板，但是里面的页面级别的服务会注入不了。
当然这也不是不能解决，比如我可以把需要注入的服务，塞到column里，然后组件再从column里获取，但是用起来可能也会感觉有点怪。

然后现在过滤组件已经是封了一层，把primeng的表格过滤器p-columnFilter抄了过来，用zorro的重写了视图，column-filter-st是连接column-filter与st的，主要是根据st的column属性自动设置column-filter所需要的属性。

不过之前没想过再封一层，现在看来如果要进一步减少样板代码，再封一层也是个很好的选择，起码3行可以变1行，而且也有利于后期维护。
