### ISSUE TITLE
执行package.json中的theme scripts重新生成asserts下的css文件后暗色主题预设状态的标签背景色错误

### ISSUE THREAD

**Issue by jaydonshi** [cipchk/ng-alain#2300]
### Steps to reproduce
1. yarn run theme
2. 切换dark主题后使用预设状态的标签，例如```<nz-tag nzColor="processing">processing</nz-tag>```

### What is expected?
切换dark主题后使用预设状态的标签，tag背景色应匹配暗色主题

### What is actually happening?
切换dark主题后使用预设状态的标签，tag背景颜色为亮色

| Environment | Info |
|---|---|
| ng-alain | 13.2.0 |
| Browser | Google Chrome 105.0.5195.102 |

**Comment by jaydonshi** [comment]
如图：
<img width="117" alt="1C895E91-82D9-4F2A-A0AA-9BDD8FA5F59E" src="https://user-images.githubusercontent.com/20196853/189278896-47c1e063-ec6e-499d-ba2b-4403163a79e7.png">

使用颜色就没有问题

<img width="92" alt="D02E2BC4-E45F-45F5-AD18-D7CBBDCFF081" src="https://user-images.githubusercontent.com/20196853/189279235-c54825f2-383c-4564-813a-64bddfb7f1f2.png">

**Comment by cipchk** [comment]
[demo](https://ng-alain.surge.sh/#/widgets) 中有类似的 tag，并且在 Dark 模式是正常的。

你可以检测一下生成后的 DOM 的 class 是不是存在被覆盖的问题。

**Comment by jaydonshi** [comment]
> [demo](https://ng-alain.surge.sh/#/widgets) 中有类似的 tag，并且在 Dark 模式是正常的。
> 
> 你可以检测一下生成后的 DOM 的 class 是不是存在被覆盖的问题。

默认情况下是没问题。我是用ng-alain-plugin-theme -t=themeCss重新生成了src/assets/style.dark.css文件，此时就会出现我描述的问题。我在github上clone了干净的ng-alain项目，直接ng-alain-plugin-theme -t=themeCss后也会有这个问题。检查了重新生成的style.dark.css确实是有问题的，感觉是ng-alain-plugin-theme的问题。

<img width="633" alt="image" src="https://user-images.githubusercontent.com/20196853/189793501-7a02cb43-89ae-45eb-b13e-38882a29127a.png">

**Comment by cipchk** [comment]
我尝试了一下，一切正常, png：

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2987467/190082349-e69f7f72-45e8-4d6e-be49-f1c88db5495d.png">

**Comment by jaydonshi** [comment]
使用方式不一样吗？我是重新生成style.dark.css后，使用theme-btn在运行时切换到暗色主题，我看了下切换后会加载style.dark.css，这个重新生成的css里覆盖的backgroud颜色有问题，你图片里是直接.ant-tag-processing就改变了background

> 我尝试了一下，一切正常, png：
> 
> <img alt="image" width="1036" src="https://user-images.githubusercontent.com/2987467/190082349-e69f7f72-45e8-4d6e-be49-f1c88db5495d.png">

**Comment by jaydonshi** [comment]
升级到13.5.2问题解决
