### ISSUE TITLE
st-filter 自定义模板时，手动设置 STColumnFilter.default=true时，无法刷新表格

### ISSUE THREAD

**Issue by zbrongyaozb** [cipchk/ng-alain#2301]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-yedtgu?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-yedtgu?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce

自定义模板，过滤数据的存储没有走本来的menus那一套，采用了自定义的逻辑。
为了使过滤图标高亮，我在自行触发刷新后，更改了STColumnFilter.default=true；
之后发现表格无法刷新了，即st.reload没反应。

检查了下源码，问题应该是出在STDataSource.getReqFilterMap这个方法上
```
private getReqFilterMap(columns: _STColumn[]): { [key: string]: string } {
    let ret = {};
    columns
      .filter(w => w.filter && w.filter.default === true)
      .forEach(col => {
        const filter = col.filter!;
        const values = this.getFilteredData(filter);
        let obj: { [key: string]: NzSafeAny } = {};
        if (filter.reName) {
          obj = filter.reName!(filter.menus!, col);
        } else {
          obj[filter.key!] = values.map(i => i.value).join(',');
        }
        ret = { ...ret, ...obj };
      });
    return ret;
  }
```
发现判断的时候是用 ===true，
但是高亮时判断有值即可，所有我把 STColumnFilter.default=true；改成了 STColumnFilter.default= 1 as any；

不能刷新的问题解决了，但是当我想消除图标的高亮状态时，又发生了问题，我清除高亮是直接用的STColumnSource.cleanFilter方法，
```
cleanFilter(col: _STColumn): this {
    const f = col.filter!;
    f.default = false;
    if (f.type === 'default') {
      f.menus!.forEach(i => (i.checked = false));
    } else {
      f.menus![0].value = undefined;
    }
    return this;
  }
```

这回没办法了，只能重写这个方法，索性也是解决了：
```
function cleanFilter(col: _STColumn) {
  const f = col.filter!;
  f.default = false;
  if (f.menus) {
    if (f.type === 'default') {
      f.menus.forEach(i => (i.checked = false));
    } else {
      f.menus[0].value = undefined;
    }
  }
  col.filter = { ...col.filter };
}

```

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| ng-alain | 14.0.0 |
| Browser | 105 |

---
虽然都临时解决了，但是希望可以从源码层面修复一下。

**Comment by cipchk** [comment]
我不清楚你是如何自定义 filter，DEMO 中并没有任何相关的代码，可以提供一下相关的代码。

另外关于自定义 filter 图标高亮问题，这里的 `default` 会在内部做修正，比如当类型为 `default` （默认）会校验 `menus` 内是否携带 `checked` 为 `true` 的选项。

**Comment by zbrongyaozb** [comment]
stackblitz 的模板方便提供个14的版本吗，现在13的这个版本，自定义过滤器的时候，初始化阶段就会报错。
好像是13.5.0的版本的时候做过一次修复，说到这好像我自行改package.json好像大概也行。

自定义过滤的思路可以先说一下。
就用了个过滤图标了，剩下的模板自定义，按钮也自定义，然后点击确定过滤的时候，把过滤的数据存到service里，req的预处理函数process会拿到这些数据，然后处理http的请求参数。

所以我点击自定义的确定按钮后，要把default改成1，这样按钮就高亮了。(改成ture查询会无法进行，这个上面提到过)

然后我清除高亮本来是这么写的：
```
function cleanFilter(col: _STColumn, columnSource: STColumnSource) {
  columnSource.cleanFilter(col);
  col.filter = { ...col.filter };
}
```
用了as any 大法拿到了私有的columnSource，但是这里也报错死掉了，主要是cleanFilter方法对menus做了非空断言。
所以没办法代码就改成了上面写的那样。
另外这个清除过滤，除了自定义过滤器会用，自带的的过滤器也会用，过滤条件以标签的形式可视化展示给了用户，用户点掉标签的时候，过滤条件也会清除。
我不确定自己塞个假的menus会怎么样，可能会和本来的过滤逻辑产生冲突，主要也是觉得有点多余就没大尝试。

其实本质上的需求就是要手动控制过滤图标的高亮与否。

**Comment by cipchk** [comment]
@zbrongyaozb 是需要额外 `menus` ，可以给个 `menu: [{value: undefined}]` 之类的；当 `type` 为 `custom` 时应该修复 `menus` 空值问题，这的确是一个bug，我在另一个[PR](https://github.com/ng-alain/delon/pull/1527/files#diff-e8b49fa5472c00805571d942acdb31943f1ead5f9ad77667789ae0651d3f9514R228)已经修复过，试着临时加上 `menus` 值。

> [Stackblitz模板](https://stackblitz.com/edit/ng-alain-setup?file=src%2Fapp%2Fapp.component.ts)已更新。

**Comment by zbrongyaozb** [comment]
@cipchk 大佬，demo链接已更新，中秋快乐哈

**Comment by cipchk** [comment]
加上 

```diff
    this.columns[2].filter = {
      type: "custom",
      custom: this.filter,
+    menus: [{value: undefined}]
    };
```

看起来就一切正常了，如同我前面说的，我在另一个 [PR](https://github.com/ng-alain/delon/pull/1527/files#diff-e8b49fa5472c00805571d942acdb31943f1ead5f9ad77667789ae0651d3f9514R228) 中修复过 `type: 'custom'` 时会自动修正 `menus` 参数，暂时可以先加上可以修复该问题。
