### ISSUE TITLE
路由复用标签刷新错误。

### ISSUE THREAD

**Issue by ttnkh21** [cipchk/ng-alain#2302]
### Reproduction link
[https://github.com/ng-alain/ng-alain](https://github.com/ng-alain/ng-alain)

### Steps to reproduce
添加路由复用标签后，
打开多个路由并右键复用标签，
刷新其中任意一个，
触发OnReuseInit事件的都是最后一个打开的路由Component。

### What is expected?
刷新应该触发当前激活的标签的OnReuseInit

### What is actually happening?
刷新实际触发的是最后一个打开标签的OnReuseInit

| Environment | Info |
|---|---|
| ng-alain | 14.0.0 |
| Browser | 谷歌最新 |

**Comment by cipchk** [comment]
现在被复用的路由需要增加 `(attach)` 事件才行，将:

```diff
- <router-outlet (activate)="reuseTab.activate($event)"></router-outlet>
+ <router-outlet (activate)="reuseTab.activate($event)" (attach)="reuseTab.activate($event)"></router-outlet>
```

即可。

**Comment by ttnkh21** [comment]
好的，解决了
