### ISSUE TITLE
如何让请求实现自动刷新 token？

### ISSUE THREAD

**Issue by forecho** [cipchk/ng-alain#2304]
### Reproduction link
[https://github.com/cashwarden/web-v2](https://github.com/cashwarden/web-v2)

[测试地址](https://cashwarden-web-v2-forecho.vercel.app/#/passport/login)
测试账号 admin@gmail.com 密码 123456

登录之后 https://cashwarden-web-v2-forecho.vercel.app/#/ledger/index 页面可以用来测试。为了方便测试，我后台的接口 token 设置了 30 秒过期。

### Steps to reproduce
登录成功之后 token，等 token 过期，无法走到刷新 buildAuthRefresh 

### What is expected?
我就是想实现 token 过期自动刷新 token 功能

### What is actually happening?
token 过期之后跳到登录页面了

| Environment | Info |
|---|---|
| ng-alain | 14.0.0 |
| Browser | 105.0.5195.125 |

**Comment by cipchk** [comment]
根据 jwt 标准提供的过期值务必是 exp，见 [4.1.4](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.4)。

> 当使用一项标准时，请严格遵守它。

**Comment by forecho** [comment]
@cipchk 感谢你的抽空回答。可能是我的描述有问题，让你产生了误解。

我的问题是，如何触发 refreshToken，buildAuthRefresh 和 tryRefreshToken 我都试过了，都无法成功。

我想实现用 refresh_token 自动去刷新 token

**Comment by forecho** [comment]
结论就是不要用 JWTInterceptor 而是要用 SimpleInterceptor

我后端用的是 oauth2 ，返回的 token 是一个 JWT 格式的 token 所以我把默认的改成 JWTInterceptor 了

JWTInterceptor 不走 refresh token
