### ISSUE TITLE
版本8升级到9后报错：Variable@layout-gutter is undefined in ..node_modules\@delon\theme\layout\default\_header.less

### ISSUE THREAD

**Issue by hackeryutu** [cipchk/ng-alain#2311]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
版本8升级到9后报错：Variable@layout-gutter is undefined in ..node_modules\@delon\theme\layout\default\_header.less

### What is expected?
不报错

### What is actually happening?
Variable @layout-gutter is undefined
      in node_modules/@delon/theme/layout/default/_header.less (line 157, column 0)

| Environment | Info |
|---|---|
| ng-alain | 11.10.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
检查一下以下几个文件是否同步，如果没有参照修改一下：

- https://github.com/ng-alain/ng-alain/blob/master/src/styles.less
- https://github.com/ng-alain/ng-alain/blob/master/src/styles/theme.less

**Comment by hackeryutu** [comment]
src/styles.less

@import '~@delon/theme/system/index';
@import '~@delon/abc/index';
@import '~@delon/chart/index';
@import '~@delon/theme/layout/default/index';
@import '~@delon/theme/layout/fullscreen/index';

@import './styles/index';
@import './styles/theme';

src/styles/theme.less
没任何东西

我发现@layout-gutter被定义在assets/alain-default.less文件下

也把scripts文件夹下的color-less.js移动到项目下了, 不知道为什么还是找不到定义。。


package.json

 "scripts": {
    "ng": "ng",
    "start": "npm run color-less && ng serve -o",
    "build": "npm run color-less && ng build --prod ",
    "test": "ng test",
    "lint": "npm run lint:ts && npm run lint:style",
    "e2e": "ng e2e",
    "analyze": "npm run color-less && ng build --prod  --stats-json",
    "test-coverage": "ng test --code-coverage --watch=false",
    "color-less": "node scripts/color-less.js",
    "lint:ts": "ng lint --fix",
    "lint:style": "stylelint \"{src}/**/*.less\" --syntax less",
    "lint-staged": "lint-staged",
    "tslint-check": "tslint-config-prettier-check ./tslint.json",
    "hmr": "ng serve -c=hmr",
    "tslint": "tslint -p tsconfig.json",
    "tslint-fix": "tslint --fix -p tsconfig.json"
  },

**Comment by cipchk** [comment]
除此之外，看一下 `angular.json` 的 [stylePreprocessorOptions](https://github.com/ng-alain/ng-alain/blob/master/angular.json#L43) 配置。
