### ISSUE TITLE
sf升级至14.1.1后schema中定义的array类型的visibleIf失效

### ISSUE THREAD

**Issue by jaydonshi** [cipchk/ng-alain#2316]
### Reproduction link
[https://codesandbox.io/s/vf-14-1-1-rkvytb?file=/src/app/app.component.ts](https://codesandbox.io/s/vf-14-1-1-rkvytb?file=/src/app/app.component.ts)

### Steps to reproduce
如果schema按如下方式定义，array中object定义的visibleIf将失效：

```
schema: SFSchema = {
    properties: {
      list: {
        type: "array",
        minItems: 1,
        title: "test",
        items: {
          type: "object",
          properties: {
            status: {
              type: "string",
              title: "状态",
              enum: [
                { label: "1", value: "1" },
                { label: "2", value: "2" },
                { label: "3", value: "3" }
              ]
            },
            name: {
              type: "string",
              title: "姓名",
              ui: {
                visibleIf: {
                  status: (val: string) => {
                    console.log(`${val}`);
                    return val === "1";
                  }
                }
              }
            }
          }
        },
        default: [{}]
      }
    }
  };
```

### What is expected?
visibleIf应可以正常控制显隐

### What is actually happening?
visibleIf无作用

| Environment | Info |
|---|---|
| ng-alain | 14.1.1 |
| Browser | Google Chrome 105.0.5195.125 |

---
相同场景用14.1.0版本测试正常

https://codesandbox.io/s/vf-14-1-0-zuuy5o?file=/src/app/app.component.ts

**Comment by cipchk** [comment]
应该是 https://github.com/ng-alain/delon/pull/1531 引起的，估计缺少这一部分的测试用例，导致无法测出一些细节，请暂时回退到 `14.1.0`。
