### ISSUE TITLE
st组件的type='img'无效

### ISSUE THREAD

**Issue by snowchenlei** [cipchk/ng-alain#2319]
### Reproduction link
[https://stackblitz.com/edit/angular-l9m2xx?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-l9m2xx?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
配置st组件column的type='img'
`import { ImageModule } from '@delon/abc/image';`
看报错应该是ImageModule 被删了

### What is expected?
显示图片预览

### What is actually happening?
图片没有显示

| Environment | Info |
|---|---|
| ng-alain | 14.1.1 |
| Browser | edge 106.0.1370.52 |

**Comment by cipchk** [comment]
我会重新修改 DEMO，若有需要自行编写 ImgWidget
