### ISSUE TITLE
官网demo，主题色设置不起作用

### ISSUE THREAD

**Issue by wucaibin** [cipchk/ng-alain#2320]
### Reproduction link
[https://github.com/ng-alain/ng-alain](https://github.com/ng-alain/ng-alain)

### Steps to reproduce
右侧设置主题色->预览，没有变化，刷新，重新登录都没有变化。在theme.less中设置也没有效果。

| Environment | Info |
|---|---|
| ng-alain | 14.1.1 |
| Browser | chrome  103.0.5060.114 |

**Comment by cipchk** [comment]
修改 `theme.less` 是有效的：

```less
// You can directly set the default theme
// - `default` Default theme
// - `dark` Import the official dark less style file
// - `compact` Import the official compact less style file
@import '@delon/theme/theme-default.less';

// ==========The following is the custom theme variable area==========
// The theme paraments can be generated at https://ng-alain.github.io/ng-alain/
@primary-color: #f50;
```

至于 `color.less` 估计是生成问题，我会在近期解决。
