### ISSUE TITLE
swagger api生成器中增加tag字典

### ISSUE THREAD

**Issue by rxxy** [cipchk/ng-alain#2325]
## What problem does this feature solve?
之前为了方便阅读swagger文档，api的tag都使用了中文，所以在生成api代码的时候也在路径和类XXService使用了中文的tag。
如果可以在生成api代码的时候做tag的中英文转换，则可以文档和客户端SDK兼得，互不影响。

## What does the proposed API look like?
生成api的时候指定一个json字典文件，用于tag名称转换，或者指定一个文件/函数(不知道可不可行?)自定义转换逻辑。

![5Z`GB~~`GQ8H4OCYVWW M3](https://user-images.githubusercontent.com/14834156/199388697-c481d6d2-ea43-4399-bdd2-8dc075e9601a.png)

**Comment by rxxy** [comment]
如果可以指定函数的话，方法名也可以转换，swagger要求在同一个group内的operateId必须是唯一的，但实际上大家更多用tag来作为一个命名空间，一个tag对应了生成代码的一个service，与其他的tag或service都是独立的命名空间。

所以这就可以在生成api的时候在operateId后面增加随机字符唯一化operateId，比如page_12，在生成代码时去掉最后一个下划线后面的字符，拥有一个简洁的名字。

事实上后端java在写controller的时候，每个controller的方法名可能都差不多，xxlist, xxpage。只是经过swagger标准后变形了。

命名空间从后端的Controller => swagger的group => 客户端的Service

有时候在想是不是把swagger的group用来做api的分组才是对的，但是大家好像都没有这么做。

**Comment by cipchk** [comment]
Swagger 标准里面就是采用 tags 来分组的，见 [Grouping Operations With Tags](https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/?sbsearch=group)。
