### ISSUE TITLE
Array类型数据能否新增table组件展示

### ISSUE THREAD

**Issue by wyq-L** [cipchk/ng-alain#2326]
## What problem does this feature solve?
table组件可以前端分页的方式  展示大量的数据
相比array组件可以减少modal空间 ，某些场景下不会出现纵向滚动条

## What does the proposed API look like?
widget新增 table 类型

**Comment by wyq-L** [comment]
![图片](https://user-images.githubusercontent.com/51746356/199633375-e1e0a593-d6ec-49b3-9d04-8eab24c5b163.png)

类似这种

**Comment by cipchk** [comment]
可以自定义一个小部件，参考 [array](https://github.com/ng-alain/delon/tree/master/packages/form/src/widgets/array) 即可，只不过换一种方式。
