### ISSUE TITLE
st表格自定义按钮支持动态设置className

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2331]
## What problem does this feature solve?
遇到一个场景，针对某记录首次操作时按钮显示为橙色，除首次之外显示为蓝色。原因是该按钮在业务上是允许重复操作的，采用颜色来快速区分它有没有被操作过。

目前我的解决方案是定义2个按钮来替代，稍显繁琐。

## What does the proposed API look like?
希望className可以指定函数，函数动态返回样式类名。

同理，亦希望text属性也可以动态设置。

**Comment by cipchk** [comment]
`text` 属性我记得是支持 `function` 的

**Comment by ococl** [comment]
艾玛ya！那句话是多余的，一直以为删掉了呢！😄

**Comment by ococl** [comment]
补充：希望icon属性也同时支持一下！
