### ISSUE TITLE
nz-modal with st fixed has some error

### ISSUE THREAD

**Issue by cai1035752265** [cipchk/ng-alain#2332]
### Reproduction link
[https://stackblitz.com/edit/angular-kpgat5?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-kpgat5?file=src/app/app.component.ts)

### Steps to reproduce
使用表格st，设置scroll，和>=2列设置fixed:'left'或者’right‘，并将这个st放到nz-modal上

### What is expected?
弹框中的表格固定列正常显示

### What is actually happening?
实际上弹框中的表格固定列从第二列起，left就出现了异常
![1668562487706](https://user-images.githubusercontent.com/33340516/202062030-df15f879-a6ec-4343-b454-d0f6a740ce4b.jpg)

| Environment | Info |
|---|---|
| ng-alain | 14.2.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
我 Chrome (`版本 107.0.5304.110（正式版本） (x86_64)` 看起来一切都正常：

<img width="794" alt="image" src="https://user-images.githubusercontent.com/2987467/202087738-a12b1780-863a-48f7-92f4-94c7366d9081.png">

**Comment by cai1035752265** [comment]
我这边的chrome是101.0.4951.41（正式版本） （64 位），我重新点开自己的链接发现是正常的，刷新后或者增加一列fixed:’right‘结果又出现了这种情况。不知道你那边是否能复现，最头疼的是，自己的本地项目是必出现该问题。

**Comment by cai1035752265** [comment]
同时我还发现，如果是无数据显示no-data的话，一开始也是正常的，刷新后偶现宽度缩小问题
![image](https://user-images.githubusercontent.com/33340516/202111143-5d2d3dbd-4b5d-4363-a094-892e75228fba.png)

**Comment by cipchk** [comment]
试着尝试升级  chrome ，我这里不管怎么试都是正常的。亦或是你使用 `nz-table` 是否也有相同情况。

**Comment by cai1035752265** [comment]
这边试了升级，结果不变，我发现这个bug应该是ng-zorrode ,我是用nz-modal和nz-table有同样的问题，我去他们那边提issue，该问题可关闭
