### ISSUE TITLE
ST组件固定列边距样式优化。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2336]
### Reproduction link
[https://github.com/ng-alain](https://github.com/ng-alain)

### Steps to reproduce
如图，当格式为small或者middle时，两侧固定列内侧，内容与边距无视觉间距。
![截屏2022-11-22 14 53 25](https://user-images.githubusercontent.com/2936579/203245189-11ef9346-f828-436f-bcc9-1171ac4732c8.png)

### What is expected?
增加间隔，如图，设置size为defult时，视觉效果正常。
![截屏2022-11-22 14 54 05](https://user-images.githubusercontent.com/2936579/203245320-09a081ae-d45c-4ef2-a8b6-d8e28cfa8f52.png)

### What is actually happening?
增加间隔

| Environment | Info |
|---|---|
| ng-alain | 14.2.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
当 `widthMode` 的行为为 `truncate` （也是默认行为），会导致这种情况，主要因素还是因为固定列时指定了 `width` 后需要在 `td` 上借助 `overflow: hidden` 才会生效，这便会导致阴影失效。这一情况目前没有好的办法，但相比较固定列带来的收益大于阴影（为何在 `size` 默认下会感觉不明显，主要是因为其 `padding` 足够宽，其实还是小的。）

而在 `widthMode` 的行为为 `wrap` 是一切正常。但还是没有间距，这是BUG，会修复此问题。而上面的情况不再修复范围之列。
