### ISSUE TITLE
STColumnt的STChange在radio和checkbox事件中，可以获取到对应行号

### ISSUE THREAD

**Issue by aLoNeIT** [cipchk/ng-alain#2337]
### What is expected?
在radio和checkbox回调带的数据中，可以获取到当前操作行的行号。

### What is actually happening?
radio事件中只有当前操作行的数据，没有行号；
checkbox事件中只能获取到当前所有选中行的数据，没有行号，也无法知晓当前选中的这行是哪一行

| Environment | Info |
|---|---|
| ng-alain | 14.2.0 |
| Browser | all |

**Comment by aLoNeIT** [comment]
另外期望统一一下rowClassName和clickRowClassName作用。结合radio和checkbox，统一按照当前行的checked状态来决定是否显示行选中效果，让用户只需要自行决定行选中样式，而不需要自己写业务逻辑处理什么情况下应该变为行选中。

**Comment by cipchk** [comment]
`rowClassName` 支持全局定义，其实大可在全局定义中，统一自行处理是否根据 `checked` 状态来调整行样式的。

关于 `index` 索引，如果有需要可以 `this.st.list.indexOf(STData)` 就可以得到。

**Comment by aLoNeIT** [comment]
> 

radio中只返回了一个数据，我可以用this.st.list.indexOf(STData)获取，但是checkbox事件中是一个数组，我无法获取最后一次选中的数据，除非数组中的元素排序是按照点击顺序排序的。

其次rowClassName存在触发时机较为缓慢的情况。在我当前项目中，使用rowClassName来变更选中行样式，存在非常明显的延迟，但是clickRowClassName却非常及时（这应该是归功于他直接dom操作，而非等待ng变更检测机制触发）
我期望的是拥有一个及时的且统一的方法来做行选中处理，比如提供主动的触发行选中样式变更的方法，其方法内部使用dom操作的方式，这样交互体验非常好。

PS：以前提过选中延迟问题，但是简易页面无法复现。如果可以，QQ群内您有时间了，我将我们测试环境修改为rowClassName方式设置选中行，然后您来看看效果

**Comment by cipchk** [comment]
关于 `rowClassName` 相关问题，可以重新提交新的 ISSUES。
