### ISSUE TITLE
是否可以将ST组件的列配置为undefined|null|{}时，默认不渲染表格。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2338]
### Reproduction link
[https://github.com/ng-alain](https://github.com/ng-alain)

### Steps to reproduce

正常情况下，`<st [req]="{ lazyLoad: true }"` 可以设置表格不加载数据。但他会先渲染表格。

如果我的表格配置是从后端获取，则我需要先随便设置一个columns的配置信息供表格渲染，等从后端获取配置后，使用`st.resetColumns()`现次渲染表格。

那么，是否我直接传入的columns为假值时，不渲染。而获取完后再渲染呢？

| Environment | Info |
|---|---|
| ng-alain | 14.2.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
数据是否开始加载，我还是不建议以是否存在 `columns` 为基准，依然保持 `lazyLoad` 的控制权限。不过让 `column` 支持 `null`、`undefined` 还是能提供一些便利的。

**Comment by xingkoo** [comment]
确实，数据加载由`lazyLoad`控制，
如需后台提供表格列配置，则设置`columns`和`lazyload`为假值。当获取到配置信息后，使用`this.st.resetColumns({ columns: columns, emitReload: true });`来渲染及加载数据。能省很多事，完美。
