### ISSUE TITLE
ST中的按钮组自动折叠到更多按钮下的功能

### ISSUE THREAD

**Issue by aLoNeIT** [cipchk/ng-alain#2340]
## What problem does this feature solve?
在某些业务场景中，右侧按钮会根据某个数据来决定是否显示，如果非“更多”按钮组的其他按钮全都不显示，那么界面上就只剩下更多按钮，在UI交互上显得不人性化（明明还有很多按钮可以使用，为什么都被折叠到了“更多”中）
极端情况下会发生鼠标放置到更多按钮上，都不会显示其他按钮（因为其他按钮也被iif所隐藏了）
这种情况下在父组件上没有好的方案可以自行处理，思来想去可能还是在组件内部增强该功能更好。

## What does the proposed API look like?
col:STColumnt={
	text: '操作区',
	buttons:[
        {text: '编辑'},{text:'删除'},{text:'查看',folded:true},{text:'测试',folded:true}
    ],
    foldLength:2
};
foldLength代表超过多少个按钮就进行折叠处理，默认为0
每个按钮有一个folded属性，代表该按钮是否会被折叠，默认false
当渲染时，可以通过计算来让ST组件内部决定哪些按钮会被折叠（计算时要排除视觉上不显示的按钮，包括iif和acl受到影响的按钮）

**Comment by cipchk** [comment]
有内置的呀，参考 [maxMultipleButton](https://ng-alain.com/components/st/zh?#API)。
