### ISSUE TITLE
基于ng-alain写一个增强库，希望能够获得作者一些帮助。

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2341]
## What problem does this feature solve?
已经写了一些基础功能：https://github.com/future-cube/fc-ng-lib
目前实现了一个简单的功能，从通过服务，从后端获取表格列配置及数据文件【全局注入时指定请求接口地址】。

后续会处理一些通过前端来管理列配置、表单结构生成等功能。

## What does the proposed API look like?
- 自定义一些SF的组件
- 自定义一些ST的列模板
- 一些其他基于ng-alain的增强实现

> 想类似@delon，分不同的包来实现，以供其他项目分别使用。

由于技术能力有限，对第三方包的开发理解有限，

所以作者能否提供一个base 类库，加简单的开发说明，以供有类似想法的朋友快速开始，
如时间有限，不方便提供的话，能否提供一些参考资料。
感谢！

**Comment by cipchk** [comment]
可以试一下 [Angular Libraries](https://angular.io/guide/creating-libraries) ，本身就有提供一个工程项目内使用多个类库，并可以将这些类库发布到 NPM 等上面。而且非常简单。事实上，@delon/* 系列想要换成 Angular Libraries 也是可以的。

**Comment by xingkoo** [comment]
现在就是直接在`ng-alain`的基础上，通过这种方式，使用`ng  g library lib-name`生成的类库。
但似乎要想做成类似`@delon/*`这样的多个类库，还是差很多工作量。
个人觉得应该是在script上的差别。
我先尝试着使用目前的框架，先把需要的功能做出来试试。

**Comment by cipchk** [comment]
一样的，只不过 `@delon` 直接使用的是 https://github.com/ng-packagr/ng-packagr  来打包，本质还是一样的。

**Comment by devcui** [comment]
直接发你自己写的包，然后peerDependence上加上@delon/xxx @delon/xxx ng-alain这种信息

**Comment by cipchk** [comment]
`peerDependence` 是表明依赖的情况，这的确是需要的。
