### ISSUE TITLE
STColumn的maxMultipleButton属性，计算显示按钮属性时将“更多”按钮也计算为一个按钮计数

### ISSUE THREAD

**Issue by aLoNeIT** [cipchk/ng-alain#2344]
## What problem does this feature solve?
假定配置maxMultipleButton为3，期望展示效果是：
1：如果原本按钮数<=3个，则不显示更多按钮
2：如果原本>3个，则显示2个正常按钮，再加上一个更多按钮，其他(n-2)个按钮都归到更多按钮下
主要目的是保证按钮区按钮数是和maxMultipleButton设置的值一致

## What does the proposed API look like?
无

**Comment by cipchk** [comment]
你也可以理解为保留的数量 - 1
