### ISSUE TITLE
util/format/validate.ts isNum 对科学计数法的数字判断错误

### ISSUE THREAD

**Issue by gemron** [cipchk/ng-alain#2349]
### Reproduction link
[https://ng-alain-setup-9cmxi2.stackblitz.io](https://ng-alain-setup-9cmxi2.stackblitz.io)

### Steps to reproduce
https://ng-alain-setup-9cmxi2.stackblitz.io

### What is expected?
true

### What is actually happening?
false

| Environment | Info |
|---|---|
| ng-alain | 14.3.0 |
| Browser | chrome 108.0.5359.125 |

---
isNaN可以正确判断出 1.123e-10 为数字 ， util/format/validate.ts isNum  判断为非数字

**Comment by cipchk** [comment]
临时解决办法可以在 angular 启动时更新一下默认正则：

```ts
REGEX_STR.num =`(([-+]?\\d+\\.\\d+)|([-+]?\\d+)|([-+]?\\.\\d+))(?:[eE]([-+]?\\d+))?`;
```
