### ISSUE TITLE
增强SfComponent组件的Object挂件UI样式

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2357]
### Reproduction link
[https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/object/object.widget.ts#L44](https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/object/object.widget.ts#L44)

### Steps to reproduce
参见上方源码位置。

### What is expected?
使用Object Widget支持  父级UI的`'*'`配置，或 使用 `a.b.c` 格式配置的UI样式。
如下，`value`的属性可分两列展示，
```
{
  type: 'object',
  properties: {
    key: { type: 'string' },
    value: {
      type: 'object',
      properties: {
        type: { type: 'string', title: '数据类型', ui: { grid: { span: 12 } } },
      }
    }
  }
}
```
希望能够使用以下方式,来设置Object对象的UI参数：
```
{
  type: 'object',
  properties: {
    key: { type: 'string' },
    value: {
      type: 'object',
      properties: {
        type: { type: 'string', title: '数据类型'},
      }
    }
  },
  ui: {
    '*': { grid: { span: 24 } },
    '$value.type': { grid: { span: 24 } }, // a.b.c格式配置
}
```

### What is actually happening?
能够让Object的UI参数与Schema解耦。

| Environment | Info |
|---|---|
| ng-alain | 15.0.0 |
| Browser | chrome |

**Comment by xingkoo** [comment]
`spanLabelFixed<=0` 时被抛弃。https://github.com/ng-alain/delon/blob/89c7b677c4/packages/form/src/sf-fixed.directive.ts#L13 
`spanLabel=0` 时,同样未生效

**Comment by cipchk** [comment]
`ui` 参数，跟 `schema` 足够分离，暂不考虑更复杂的写法。
