### ISSUE TITLE
对模态框和抽屉的标题进行增强

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2358]
## What problem does this feature solve?
合理复用标题右侧。有些场景下，希望能够增加对空间的复用。
可以直接放置副标题或者链接、按钮到标题行右侧，类似Card组件标题右侧区域。

## What does the proposed API look like?
```
const extra: string | TemplateRef<void> = '副标题';
this.drawerHelper.create('Edit', FormEditComponent, { i }, {extra, ...other}).subscribe(res => this.load());
```

**Comment by xingkoo** [comment]
如果可以,模态框也可以增加同样参数

**Comment by cipchk** [comment]
见 `drawerOptions` 属性等同于原生的 `NzDrawerOptions`。

> 静态也有类同 `modalOptions`

**Comment by xingkoo** [comment]
可能是我的描述不够明确。我想表达的是，增加一个标题右侧的可编辑区域，类似Card组件标题右侧可以自定义一个区域一样。见下方图片中标说明.

我查阅了NG-ZORRO的[源码](https://github.com/NG-ZORRO/ng-zorro-antd/blob/923f14eba1a4caa010d230c08a96ca0b344c65ea/components/modal/modal-container.component.ts#L44)，事实上，他可以接受一个模板传入，然后整体渲染为标题。
NG-ALAIN只是原样把这个标题（字符串或者模板）传入并渲染，目前并无法达到相应的目的。

![image](https://user-images.githubusercontent.com/2936579/216140976-706a6940-393e-4da3-9c39-51f3c517937a.png)

**Comment by cipchk** [comment]
`DrawerHelper.create(title)` 也是支持 `string | TemplateRef<NzSafeAny>` 的，这一点跟原生是保持一致的。
