### ISSUE TITLE
表单修改布局后错误渲染异常.

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2363]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-pynpks?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-pynpks?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击下面的表单，
修改布局为`搜索`，再改回`默认`时，上方的必填项错误提示视觉效果`丢失`。
修改布局为`编辑`，再改回`默认`时，上方的必填项错误提示视觉效果`正常`。

### What is expected?
变更布局时，不丢失错误视觉效果。

| Environment | Info |
|---|---|
| ng-alain | 15.0.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
`mode` 是一种[预设](https://github.com/ng-alain/delon/blob/master/packages/form/src/sf.component.ts#L140-L145)写法，这会导致 `firstVisual` 和 `liveValidate` 始终为内置的预设模式，这种配置就不要使用 `mode`，可以自行预设 。

**Comment by xingkoo** [comment]
可以强制刷新修改吗?因为我正在写一个表单配置生成器,需要根据配置信息预览表单.
或者我可以做到的是通过IF来移除再载入,来强制解决这个问题.但是这个方式不是非常优雅.

**Comment by cipchk** [comment]
不使用 `mode` 即可呀，你可以见源代码里面，其实也只是对不同参数的预设而已。
