### ISSUE TITLE
sf将标签置空后，表单控件无法满宽显示

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2367]
### Reproduction link
不需要链接，见下方截图

### Steps to reproduce

见图：
![image](https://user-images.githubusercontent.com/315716/217129695-9f3da1f4-d868-4c9c-97af-6caf29594900.png)

### What is expected?
希望标签隐藏后，控件能够满宽显示。同样如果可能，如果控件被隐藏，那么标签也应当满宽。

### What is actually happening?
控件无法满宽显示

| Environment | Info |
|---|---|
| ng-alain | 15.0.1 |
| Browser | all |

---
在自定义一些无标签控件（例如纯粹一个文本标题、一个分割线、一个表格布局、一个tab布局等）的时候非常有用~

**Comment by cipchk** [comment]
如果想拉满，可以给 `name` 设置 `spanControl: 24`；
如果想留空 label 并与 `pwd` 对齐，可以给 `name` 设置 `offsetControl: 5`；

> 目前并不支持只显示 `label` 而不显示 `control` 方式。
