### ISSUE TITLE
sf设定spanLabelFixed之后，将字段title置空，控件标签位置仍然会被占用，控件不能满宽显示

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2368]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-dr3zfg?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-dr3zfg?file=src%2Fapp%2Fapp.component.ts)

![image](https://user-images.githubusercontent.com/315716/217130348-78cbd041-d39c-47a7-b3ee-a86b48787b5f.png)

### Steps to reproduce
1. 设置spanLabelFixed的值为150；
2. 设置某字段title为''；

### What is expected?
希望标签隐藏后，控件能够满宽显示

### What is actually happening?
控件无法满宽显示

| Environment | Info |
|---|---|
| ng-alain | 15.0.1 |
| Browser | all |

**Comment by cipchk** [comment]
默认会继承父级，因此，可以这样：

```diff
  schema: SFSchema = {
    properties: {
      name: {
        title: '',
        type: 'string',
+        ui: {
+          spanLabelFixed: 0
+        }
      },
```
