### ISSUE TITLE
sf的object控件设置spanLabelFixed之后，只有第一个子控件会继承该值

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2369]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-5pra9s](https://stackblitz.com/edit/ng-alain-setup-5pra9s)

![image](https://user-images.githubusercontent.com/315716/217157490-e32b4778-a78b-4379-a9d5-81088749d6c1.png)

### Steps to reproduce
1. object定义spanLabelFixed为350；
2. root定义spanLabelFixed为100；

### What is expected?
object的子控件应当继承object的配置

### What is actually happening?
只有第一个子控件会继承object的配置

| Environment | Info |
|---|---|
| ng-alain | 15.0.1 |
| Browser | all |

**Comment by cipchk** [comment]
fixed by https://github.com/ng-alain/delon/pull/1582
