### ISSUE TITLE
sf object 模式下使用 widget.detectChanges 界面没有更新

### ISSUE THREAD

**Issue by C-racker** [cipchk/ng-alain#2370]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-tnxufk?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-tnxufk?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击选项D

### What is expected?
选项B禁用，选项3必填

### What is actually happening?
界面没有任何变化

| Environment | Info |
|---|---|
| ng-alain | 15.0.1 |
| Browser | edge/chrome 100  |

---
只有在 object 模式下会出现问题。

**Comment by ococl** [comment]
`typeProperty.widget.reset(0);`
试试这个

**Comment by cipchk** [comment]
我分两部分来回答这个问题：

### 关于渲染

不管是 `p.widget.detectChanges();` 还是 `p.cd()` 都只是调用 Angular 的重新渲染。但为什么总感觉跟我们想的结果不一致，很大的原因是所有小部件的数据加载都有一个多重数据来源，而每次 Angular 新的渲染，只是 Angular 内部机制，并不会重新去拉取数据，这样会很可怕。因此大多数情况下，当我们变更 `enum`、`asyncData` 值时，只能通过 `reset` (`typeProperty.widget.reset(typeProperty.value)`) 方法来强制重新加载数据并渲染。

### 关于Required

这里涉及到 JSON Schema 的标准实现问题，还有就是 form 的实现方式倒置的（form在创建一个 `FormProperty` 会根据`schema` 或 `ui` 参数决定最终值，且后续API接口无法同步更新引起的），仅仅通过接口去变更 `schema.requried` 也是无法使整个 JSON Schema 重绘。

以上是澄清细节问题。而关于DEMO的解决方案就是，使用 `validator` 生产错误，利用 `setValue` 来刷新相关于元素的状态，见：https://stackblitz.com/edit/ng-alain-setup-klhese?file=src%2Fapp%2Fapp.component.ts

**Comment by C-racker** [comment]
> 我分两部分来回答这个问题：
> 
> ### 关于渲染
> 不管是 `p.widget.detectChanges();` 还是 `p.cd()` 都只是调用 Angular 的重新渲染。但为什么总感觉跟我们想的结果不一致，很大的原因是所有小部件的数据加载都有一个多重数据来源，而每次 Angular 新的渲染，只是 Angular 内部机制，并不会重新去拉取数据，这样会很可怕。因此大多数情况下，当我们变更 `enum`、`asyncData` 值时，只能通过 `reset` (`typeProperty.widget.reset(typeProperty.value)`) 方法来强制重新加载数据并渲染。
> 
> ### 关于Required
> 这里涉及到 JSON Schema 的标准实现问题，还有就是 form 的实现方式倒置的（form在创建一个 `FormProperty` 会根据`schema` 或 `ui` 参数决定最终值，且后续API接口无法同步更新引起的），仅仅通过接口去变更 `schema.requried` 也是无法使整个 JSON Schema 重绘。
> 
> 以上是澄清细节问题。而关于DEMO的解决方案就是，使用 `validator` 生产错误，利用 `setValue` 来刷新相关于元素的状态，见：https://stackblitz.com/edit/ng-alain-setup-klhese?file=src%2Fapp%2Fapp.component.ts

感谢回复，收益匪浅。目前又发现个问题，是在`@delon/form 12.4.2`上最后一个必填项默认会显示错误样式，但是在15.x版本中似乎被修复了，我想知道是哪次更新修复了呢 这是复现链接 https://stackblitz.com/edit/angular-wepp9p-eox3di?file=src%2Fapp%2Fapp.component.ts
