### ISSUE TITLE
动态表单Object对象类型的两个疑似Bug

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2375]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-49kar6?file=src%2Fapp%2Fapp.component.ts,package.json](https://stackblitz.com/edit/ng-alain-setup-49kar6?file=src%2Fapp%2Fapp.component.ts,package.json)

### Steps to reproduce
以上链接可以正常生成表单，且操作无任何问题。
但同样的代码，通过`GIT`新拉取一个项目出来后，同样的代码，则存在两个问题：
1、如果使用到`spanLabelFixed`设置，则会报错`ERROR TypeError: Cannot read properties of null (reading 'style')`。
2、二级properties，使用`type:object`时，无法生成对应的属性表单。

本地Node：v18.13.0，NPM：8.9.3

这两个问题均是在使用中存在的问题，通过在线链接生成的，可以正常使用，所以重新拉了一个新的项目到本地执行，并使用同样的代码，依然存在这样的问题。

### What is expected?
修复此问题。如果可能,请优先发布该问题的修复版本，在制作可视化表格表单生成器时存在这样的问题，如果此问题不能被解决，就会被卡在这个环节了。麻烦作者了~

### What is actually happening?
出现错误

| Environment | Info |
|---|---|
| ng-alain | 15.1.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
可以暂时回退到 `15.0.x` 版本，我猜应该是 https://github.com/ng-alain/delon/pull/1582 引起的。

**Comment by xingkoo** [comment]
收到,辛苦卡色大大

**Comment by xingkoo** [comment]
我尝度拉了一个新的15.0.1版本的代码执行,同示例中的代码.
注释掉`spanLabelFixed`,以排除样式问题后,依然不能显示,但是对属性改名,即可正常使用.
很大可能,是因为`type`的属性名,可能导致的问题.
我先临时使用其他名称,获取及提交数据时,手工修改一下数据以临时可用,等后续的bug修复吧.
