### ISSUE TITLE
ReuseTabService 保持滚动条位置

### ISSUE THREAD

**Issue by w-wen-n** [cipchk/ng-alain#2379]
## What problem does this feature solve?
keepingScrollContainer,能不能设置st的滚动条位置,我试过获取document.getElementsByClassName('st')[0] as Element不行的,保存的是最外层的window滚动条,我想页面中st表格保持滚动条位置,一个页面一个表格

## What does the proposed API look like?
[keepingScrollContainer]	保持滚动条容器	string | Element

**Comment by cipchk** [comment]
没有办法知道组件是否包含 `st`，你可以自己维护一个 Service ，然后在离开时记下位置，当再回来时恢复即可，`ReuseTabService` 有提供相应的生命周期事件。
