### ISSUE TITLE
希望reuse-tab组件直接禁用当前访问页面对应的Tab的点击事件

### ISSUE THREAD

**Issue by Sev7enJames** [cipchk/ng-alain#2381]
## What problem does this feature solve?
reuse-tab组件是否可直接禁用当前选中复用Tab的点击事件，不让执行复用逻辑，因为带QueryString的url在点击后会丢失QueryString，所以你们文档上提到了不支持 QueryString 查询参数的原因。但是如果直接禁用了当前选中的复用Tab的点击不执行复用逻辑，便可以解决很多问题。

## What does the proposed API look like?
直接禁用当前选中的页面复用Tab点击事件，无需开放额外参数

**Comment by cipchk** [comment]
标签页禁用点击这个行为本身只会给用户需要上增加不必要的疑惑，暂不考虑。
