### ISSUE TITLE
sv support border

### ISSUE THREAD

**Issue by snowchenlei** [cipchk/ng-alain#2385]
## What problem does this feature solve?
sv可以像NzDescriptionsModule一样显示边框

## What does the proposed API look like?
```
<sv-container nzBordered></sv-container>
```

**Comment by cipchk** [comment]
`sv` 的实现方式导致要加边框很困难。

> 建议使用 `NzDescriptionsModule` 替代，未来 `@delon/*` 系列会因为 ng-zorro 的增强，逐渐移除一些组件。
