### ISSUE TITLE
sv 支持跨列

### ISSUE THREAD

**Issue by snowchenlei** [cipchk/ng-alain#2386]
## What problem does this feature solve?
跨列显示且不影响整体的布局。现有的col无法实现显示3列的情况下，某一个sv占据前2列，另一个sv占据最后一列

## What does the proposed API look like?
![image](https://user-images.githubusercontent.com/26211283/236609880-ace6466c-db6a-4537-9911-2bfca9569922.png)
antd是通过table的colspan实现的。希望增加类似的功能
![image](https://user-images.githubusercontent.com/26211283/236610269-e0275b67-0379-47b3-bab0-dd3705bafc65.png)

``` html
<nz-descriptions *ngIf="order">
      <nz-descriptions-item nzTitle="姓名" [nzSpan]="2">张三</nz-descriptions-item>
      <nz-descriptions-item nzTitle="面积">张三</nz-descriptions-item>
      <nz-descriptions-item nzTitle="其它材料费">张三</nz-descriptions-item>
      <nz-descriptions-item nzTitle="直接费">张三</nz-descriptions-item>
      <nz-descriptions-item nzTitle="人工费">张三</nz-descriptions-item>
    </nz-descriptions>
    <nz-divider></nz-divider>
    <sv-container *ngIf="order" col="3">
      <sv label="姓名" col="2">张三</sv>
      <sv label="面积">张三</sv>
      <sv label="其它材料费">张三</sv>
      <sv label="直接费">张三</sv>
      <sv label="人工费">张三</sv>
    </sv-container>
```

**Comment by cipchk** [comment]
是的，实现机制不同导致像跨列会很麻烦，特别是涉及到响应式时。之前就尝试过解决这个问题，但是效果并不好。

但如果再写一个类似 nz-description 的话就很没必要。
