### ISSUE TITLE
st固定列标题单元格透明问题

### ISSUE THREAD

**Issue by aLoNeIT** [cipchk/ng-alain#2389]
### Reproduction link
[https://stackblitz.com/edit/angular-sydzcy?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-sydzcy?file=src/app/app.component.ts)

### Steps to reproduce
1：设置固定列
2：设置rowClassName属性

### What is expected?
固定列的标题单元格颜色和其他单元格保持一致

### What is actually happening?
因为固定列标题单元格使用了background-color:inherit，且父元素没有配置background-color，导致当前单元格透明

| Environment | Info |
|---|---|
| ng-alain | 15.2.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
fixed by https://github.com/ng-alain/delon/pull/1598
