### ISSUE TITLE
请教是否可以在系统菜单中使用svg文件做图标的问题？

### ISSUE THREAD

**Issue by unix3000** [cipchk/ng-alain#2391]
## What problem does this feature solve?
在ng-alain中静态加载@ant-design/icons-angular/icons的图标，但图标比较少，需要使用到svg格式的图标问题，那么我需要怎么弄？

## What does the proposed API look like?
文档在详细一些。

**Comment by cipchk** [comment]
指定 `type` 参数为 `svg` 即可 https://github.com/ng-alain/delon/blob/master/packages/theme/src/services/menu/interface.ts#L12C5-L14
