### ISSUE TITLE
token在开发模式下，热更新时会消失

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2396]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce
如题，目前token是存在_token的localstroage中，热更新时会丢失登陆态，我查了一下有如下说法，是否可能因为这个原因？
```
在 Angular 开发模式下使用热更新时，以_开头的 localStorage 键可能会消失。这是因为在热更新期间，Angular CLI 使用了新的代码块来替换旧代码块，并且它会清除所有以 _ 开头的 localStorage 键。

这是因为在 Angular CLI 中，开发人员通常使用 _ 开头的键名来存储一些辅助性数据，例如调试信息或状态标记。这些键名并不是 Angular 应用程序的核心业务逻辑，而是用于辅助开发和调试过程。

因此，如果您要在 Angular 开发模式下使用 _ 开头的 localStorage 键，请注意以下几点：

不要存储关键业务数据或重要的应用程序状态。
在每次热更新之前，将所有 _ 开头的 localStorage 键移动到其他键名下。
考虑使用其他方式来存储辅助性数据，例如在内存中缓存数据或使用特定的 cookie 键名。
总之，在 Angular 开发模式下，以 _ 开头的 localStorage 键可能会消失，因此需要小心处理。
```
### What is expected?
可以避免这种情况

### What is actually happening?
热更新会导致丢失登陆token

| Environment | Info |
|---|---|
| ng-alain | 16.0.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
hotreload 有这个机制吗？我还真不清楚（能否提供一些这方面的资料），因为我一直没有遇到过，不过可以尝试全局配置里面修改 `store_key` 值。

**Comment by xingkoo** [comment]
我也不太确认这个机制，来自chatGPT的答案，没有在其他地方有查找到这个问题的资料，但事实上确实这样发生了。
改`store_key`是个好主意
