### ISSUE TITLE
generate new project @latest version error

### ISSUE THREAD

**Issue by devcui** [cipchk/ng-alain#2398]
### Steps to reproduce
ng new template --style=less && cd template && ng add ng-alain@latest

### What is expected?
success

### What is actually happening?
error

| Environment | Info |
|---|---|
| ng-alain | 16.0.1 |
| Browser | none |

**Comment by devcui** [comment]
![image](https://github.com/ng-alain/ng-alain/assets/26159886/7a6e9408-9ac4-4829-9c33-bcb0482427aa)

**Comment by devcui** [comment]
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: template@0.0.0
npm ERR! Found: stylelint@15.9.0
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^15.6.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@">= 11.x < 15" from stylelint-config-prettier@9.0.5
npm ERR! node_modules/stylelint-config-prettier
npm ERR!   dev stylelint-config-prettier@"^9.0.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by devcui** [comment]
![image](https://github.com/ng-alain/ng-alain/assets/26159886/e178c74c-ee82-40d3-b165-03707736a00f)

**Comment by devcui** [comment]
![image](https://github.com/ng-alain/ng-alain/assets/26159886/3970ee00-3e6c-4cfa-b255-55b63445d620)

**Comment by devcui** [comment]
to resolve this error:

@ng-alain/delon package need to reduce to a lower rank like this:
```json
    "stylelint": "^14.16.1",
    "stylelint-config-standard": "^29.0.0",
```

**Comment by cipchk** [comment]
As of Stylelint v15 [all style-related rules have been deprecated](https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules), so just only removed it.

See diff: https://github.com/ng-alain/ng-alain/pull/2399/files
