### ISSUE TITLE
给theme/http下面的HttpOptions增加属性声明

### ISSUE THREAD

**Issue by iotzy** [cipchk/ng-alain#2413]
## What problem does this feature solve?
In order to make a request to set HttpContext without error after using the BaseApi, BaseUrl, MakeMethod modifier,

CUSTOM_ERROR is used in the example request below
``` typescript
@BaseUrl('/foo/api/v1')
@Injectable({
  providedIn: 'root'
})
export class DatasetApiService extends BaseApi {
  @POST('/boo/List', {context: new HttpContext().set(CUSTOM_ERROR, true)})
  datasets(@Payload payload: NDataset.TListDatasetsRequest): Observable<NDataset.IListDatasetsResponse> {
    return of();
  }
}
```

## What does the proposed API look like?
HttpOptions add  attribute declaration of"content? :HttpContext"

**Comment by cipchk** [comment]
fixed by https://github.com/ng-alain/ng-alain/issues/2413
