### ISSUE TITLE
色彩页面中，Full Colors 版块的颜色不显示

### ISSUE THREAD

**Issue by dusdong** [cipchk/ng-alain#2418]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-gi5c5v?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-gi5c5v?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
https://ng-alain.surge.sh/#/style/colors
忘记了从哪个版本开始，.bg-lime-1 等色彩 css 样式就没有了

### What is expected?
 .bg-lime-1 等css样式重现显示

### What is actually happening?
.bg-lime-1 等色彩 css 样式丢失

| Environment | Info |
|---|---|
| ng-alain | 16.3.0 |
| Browser | Microsoft Edge 版本 116.0.1938.76 (正式版本) (64 位) |

**Comment by cipchk** [comment]
在 `styles/theme.less` 加入:

```less
@enable-all-colors: true;
```
