### ISSUE TITLE
期待sf增加颜色选择框支持

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2421]
## What problem does this feature solve?
见：https://ng.ant.design/components/color-picker/zh

## What does the proposed API look like?
期待支持颜色选择框

**Comment by cipchk** [comment]
`@delon/form` 一直都想着如何将一些频率不高的小部件怎么转成需要额外类库，因此，像这类频率不高的小部件建议暂时自行参考 [自定义小部件](https://ng-alain.com/form/customize) 来处理。

**Comment by ococl** [comment]
嗯，支持！

本次antd更新增加了颜色控件，故而才提出这个建议。
我现在用的是封装的一个第三方的颜色控件。
