### ISSUE TITLE
希望st表格的format能够支持异步数据，支持返回Observable<any>

### ISSUE THREAD

**Issue by ococl** [cipchk/ng-alain#2422]
## What problem does this feature solve?
列表的某个字段可能需要异步获取数据然后再展示（甚至是自定义展示），但需要在导出报表时也包含该字段时就会遇到问题，因为format不支持异步。

## What does the proposed API look like?
见上。

**Comment by cipchk** [comment]
`format` 的频率会比较高，建议在做 `st` 渲染前，先做后数据字典请求动作。

**Comment by HsinM** [comment]
It is recommended to perform the backend data dictionary request before rendering the "st" component. However, how can I ensure that, as ngOnInit() is an asynchronous method, it won't be delayed compared to the "st" request, resulting in obtaining empty values for my data?

**Comment by cipchk** [comment]
@HsinM There are many ways, such as:

- Use `@if` to delay rendering `st` until the dictionary data has been loaded
- Use `startup.service.ts` to load the dictionary data required by the system before rendering Angular
