### ISSUE TITLE
this.sf.setValue('/subjectId2', null) this.sf.value 结果不对

### ISSUE THREAD

**Issue by sdandroid** [cipchk/ng-alain#2428]
### Reproduction link
[https://stackblitz.com/edit/angular-if7hxd?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-if7hxd?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
选择个第一个select

### What is expected?
this.sf.value 里面的subjectId2的值为空

### What is actually happening?
还是之前的值

| Environment | Info |
|---|---|
| ng-alain | 16.3.0 |
| Browser | chrome |

---
this.sf.getValue('subjectId2') 的值为空。

**Comment by cipchk** [comment]
不管是 `null` 或 `undefined` 都是表示具体的值，像DEMO中可以：

```diff
- this.sf.setValue("/subjectId2", null)
+ this.sf.setValue("/subjectId2", this.i.subjectId2)
```

**Comment by sdandroid** [comment]
我想实现的逻辑是，select 选了特定的值后，清空 subjectId2 的值，提交的时候值为null | undefined
