### ISSUE TITLE
Is there a similar vs code extension i18n-ally that supports ng-alain i18n?

### ISSUE THREAD

**Issue by isccliao** [cipchk/ng-alain#2430]
## What problem does this feature solve?
When editing the program, you can directly see the translation content

## What does the proposed API look like?
https://github.com/lokalise/i18n-ally

**Comment by cipchk** [comment]
NG-ALAIN does not limit i18 internationalization behavior, you only need to rewrite [ALAIN_I18N_TOKEN](https://github.com/ng-alain/delon/blob/master/packages/theme/src/services/i18n/i18n.ts#L58C14-L58C30). [Scaffolding](https://github.com/ng-alain/ng-alain/blob/master/src/app/app.module.ts#L38) only provides default behavior.
