### ISSUE TITLE
ng add `ng add ng-alain` support for v17

### ISSUE THREAD

**Issue by iabu94** [cipchk/ng-alain#2445]
## What problem does this feature solve?
I have tried to add `ng add ng-alain` into my brand new angular v17 project. But it's giving some errors that cannot be initialized. If you provide a solution to this based on v17 standalone project, it will resolve the issues.

## What does the proposed API look like?
Need to update all the exisiting components as standalone. And when initializing process also needs to be updated based on non module application

**Comment by cipchk** [comment]
Not supported yet. We need to wait a few days after ng-zorro releases 17.0.0, coming soon.

**Comment by iabu94** [comment]
I saw a PR related to this from you. So in order to merge that, do we need to wait until ng zorro 17?

**Comment by iabu94** [comment]
@cipchk , seems the v17 is here. Hope I can get the ng in a few days.
![Screenshot_2023-11-19-19-34-26-262_com.twitter.android.jpg](https://github.com/ng-alain/ng-alain/assets/27818818/d12cb3b2-8197-4182-a7a3-801f03e437c2)

**Comment by cipchk** [comment]
Fixed by `17.0.0`

**Comment by YongChingShieh** [comment]
D:\download\my-project>ng add ng-alain
ℹ Using package manager: npm
✔ Found compatible package version: ng-alain@17.0.1.
✔ Package information loaded.

The package ng-alain@17.0.1 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot find module '@angular/cdk/schematics'
Require stack:
- D:\download\my-project\node_modules\ng-alain\utils\standalone.js
- D:\download\my-project\node_modules\ng-alain\utils\alain.js
- D:\download\my-project\node_modules\ng-alain\utils\ast.js
- D:\download\my-project\node_modules\ng-alain\utils\index.js
- D:\download\my-project\node_modules\ng-alain\ng-add\index.js
- D:\download\my-project\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\download\my-project\node_modules\@angular-devkit\schematics\tools\index.js
- D:\download\my-project\node_modules\@angular\cli\src\commands\add\cli.js
- D:\download\my-project\node_modules\@angular\cli\src\commands\command-config.js
- D:\download\my-project\node_modules\@angular\cli\src\command-builder\command-runner.js
- D:\download\my-project\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\xxxx\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
