### ISSUE TITLE
14.x版本文档无法访问

### ISSUE THREAD

**Issue by yyhdev** [cipchk/ng-alain#2454]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues](https://github.com/ng-alain/ng-alain/issues)

### Steps to reproduce
https://ng-alain.com/version/14.x

### What is expected?
可以访问

### What is actually happening?
无法访问

| Environment | Info |
|---|---|
| ng-alain | 14.3.0 |
| Browser | chorme |

**Comment by cipchk** [comment]
已归档的版本，你可以自行通过 https://github.com/ng-alain/archive-docs/blob/full/README.md 来获取文档
