### ISSUE TITLE
st export column render没有导出/0 值导出为空

### ISSUE THREAD

**Issue by saup007** [cipchk/ng-alain#2463]
### Reproduction link
[https://stackblitz.com/edit/6vhgra?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/6vhgra?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
    { title: 'test', index: 'test' },
    { title: 'mark', index: ['email', 'phone'], render: 'emailTag' },

### What is expected?
1、0 值导出不为空
2、render 可以导出

### What is actually happening?
1、0 值导出为空
2、render 导出为空

| Environment | Info |
|---|---|
| ng-alain | 17.0.5 |
| Browser | Chrome |

**Comment by cipchk** [comment]
`render` 属于 ng-template 很难做相同的计算。如果你想导出类似 render 的数据，可以自行增加 `format`，就像：

```diff
-  { title: 'mark', index: ['email', 'phone'], render: 'emailTag' },
+ { title: 'mark', index: ['email', 'phone'], format: i => `${i.email.phone} - `, render: 'emailTag' },
```

> 空值问题也是如此。

**Comment by saup007** [comment]
> `render` 属于 ng-template 很难做相同的计算。如果你想导出类似 render 的数据，可以自行增加 `format`，就像：
> 
> ```diff
> -  { title: 'mark', index: ['email', 'phone'], render: 'emailTag' },
> + { title: 'mark', index: ['email', 'phone'], format: i => `${i.email.phone} - `, render: 'emailTag' },
> ```
> 
> > 空值问题也是如此。



> `render` 属于 ng-template 很难做相同的计算。如果你想导出类似 render 的数据，可以自行增加 `format`，就像：
> 
> ```diff
> -  { title: 'mark', index: ['email', 'phone'], render: 'emailTag' },
> + { title: 'mark', index: ['email', 'phone'], format: i => `${i.email.phone} - `, render: 'emailTag' },
> ```
> 
> > 空值问题也是如此。

试了下，ok了，谢谢
```
    {
      title: 'mark',
      index: ['email', 'phone'],
      format: (i) => `${i.email} - ${i.phone}`,
      // render: 'emailTag',
    },
```


不过 number类型的 0 导出为空应该不对吧 ，string 类型是可以的。（test 列）

https://stackblitz.com/edit/6vhgra?file=src%2Fapp%2Fapp.component.ts

```
data: STData[] = Array(10000)
    .fill({})
    .map((_, index) => ({
      id: index + 1,
      picture: {
        thumbnail: `https://dummyimage.com/100x100&text=${Math.min(
          index + 1,
          30
        )}`,
      },
      email: `e${index + 1}@qq.com`,
      phone: `phone - ${index + 1}`,
      price: Math.ceil(Math.random() * 10000000) + 10000000,
      registered: new Date(),
      test: index,
    }));
```

**Comment by cipchk** [comment]
临时解决办法，返回字符串即可。

```diff
- test: index,
+ test: `${index}`,
```

**Comment by saup007** [comment]
> 临时解决办法，返回字符串即可。
> 
> ```diff
> - test: index,
> + test: `${index}`,
> ```

ok
