### ISSUE TITLE
 ng build -d=//cdn.ng-alain.com/  Error: Unknown argument: d

### ISSUE THREAD

**Issue by iceshu** [cipchk/ng-alain#2472]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues/new/choose](https://github.com/ng-alain/ng-alain/issues/new/choose)

### Steps to reproduce
 ng build -d=//cdn.ng-alain.com/

### What is expected?
构建结果带cdn地址

### What is actually happening?
无法执行

| Environment | Info |
|---|---|
| ng-alain | 17.0.5 |
| Browser | chrome |

---
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.9
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

**Comment by cipchk** [comment]
并没有 `-d` 参数（我想是不是你需要的是 `--base-href` 呢？），你可以通过 https://angular.io/cli/build#options 来了解支持的所有参数。

> 如果是用第三方 builder 插件来实现 `-d` 的话，就参考第三方文档。

**Comment by iceshu** [comment]
我看文档里有 ，我也查了 好像 angular 新的版本就是不支持打包的时候指定cdn地址的方式。但是可以用--base-href。不满足我的需求
![image](https://github.com/ng-alain/ng-alain/assets/6309056/4aff0dbe-aa2e-4f61-a75b-7e0bde94e630)

**Comment by cipchk** [comment]
这是文档 太旧了，我全更新这部分文档。若 `base-href` 无法满足，估计只能自己写个脚本，按需修改 dist 中的 `index.html` 文件 内容了。
