### ISSUE TITLE
st scroll 在Chrome 121版本滚动条黑色的

### ISSUE THREAD

**Issue by saup007** [cipchk/ng-alain#2476]
### Reproduction link
[https://stackblitz.com/edit/angular-o4ltss?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-o4ltss?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
<st> 增加 [scroll]="{ x: '1300px', y: '240px' } 

### What is expected?
保持原来的灰色

### What is actually happening?
老版本Chrome灰色，新版是黑色

| Environment | Info |
|---|---|
| ng-alain | 16.4.2 |
| Browser | Chrome 121.0.6167.85 |

**Comment by Encaik** [comment]
我这也出现了相同问题，我的解决方案是使用以下两个全局样式覆盖
@scrollbar-track-color
@scrollbar-thumb-color

![image](https://github.com/ng-alain/ng-alain/assets/26430020/8b01c1d8-8fe4-4827-8d29-f549022d7451)
从f12中可以看到是这块的样式影响了

经过测试应该还和浏览器版本有关系，edge和chrome如果更新到121版本最新的版本号就会有这个问题，之前的版本不会有这个问题
![image](https://github.com/ng-alain/ng-alain/assets/26430020/420b060c-e075-4cfa-b727-3b8b5c55b726)
如果按这个图上的说法，猜测可能是之前不会解析scrollbar-color这个样式，121版本解析了，所以导致全都变了

**Comment by saup007** [comment]
> 我这也出现了相同问题，我的解决方案是使用以下两个全局样式覆盖 @scrollbar-track-color @scrollbar-thumb-color
> 
> ![image](https://private-user-images.githubusercontent.com/26430020/300353258-8b01c1d8-8fe4-4827-8d29-f549022d7451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTg0NTYsIm5iZiI6MTcwNjYxODE1NiwicGF0aCI6Ii8yNjQzMDAyMC8zMDAzNTMyNTgtOGIwMWMxZDgtOGZlNC00ODI3LThkMjktZjU0OTAyMmQ3NDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZjI2NDY1NjZjMWNjNDIxNTJkYmVmYmRmYTdlNDg2MWQ3MTkyYzk3MDFhOWY0NjE4MjYyZjBhYjdlMzk3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-SuhBUiKrC29096FuUVJgNkTbQQh51FN32Y3i1Vmic) 从f12中可以看到是这块的样式影响了
> 
> 经过测试应该还和浏览器版本有关系，edge和chrome如果更新到121版本最新的版本号就会有这个问题，之前的版本不会有这个问题 ![image](https://private-user-images.githubusercontent.com/26430020/300358467-420b060c-e075-4cfa-b727-3b8b5c55b726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTg0NTYsIm5iZiI6MTcwNjYxODE1NiwicGF0aCI6Ii8yNjQzMDAyMC8zMDAzNTg0NjctNDIwYjA2MGMtZTA3NS00Y2ZhLWI3MjctM2I4YjVjNTViNzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NzU5NWJjODk3YTUwYjA1YTI1ODMwODY4Yzg1NDZkZWE5ZWQyY2NhZWRmMzU5NDg1OTA3ZGUzN2ZlMjdlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.34hlj4uyCtH9I3GNLHyEucGdoaJSSc8OPoDkapOO7_0) 如果按这个图上的说法，猜测可能是之前不会解析scrollbar-color这个样式，121版本解析了，所以导致全都变了

121 scrollbar 逻辑貌似变了

**Comment by cipchk** [comment]
可以设置 `@scrollbar-thumb-color: transparent`，但感觉在 mac 下还是它原生的效果好。不知道 Windows 下会是怎么样？
