### ISSUE TITLE
在ModalHelper中使用st组件，会出现 NullInjectorError: No provider for _NzContextMenuService，导致弹出框页面无法加载

### ISSUE THREAD

**Issue by skmbw** [cipchk/ng-alain#2479]
### Reproduction link
[http://github.com/skmbw/ng-alain-17.2.0](http://github.com/skmbw/ng-alain-17.2.0)

### Steps to reproduce
在ModalHelper中使用st组件，会出现 NullInjectorError: No provider for _NzContextMenuService，导致弹出框页面无法加载

### What is expected?
正常打开弹出框

### What is actually happening?
打不开弹出框

| Environment | Info |
|---|---|
| ng-alain | 17.2.0 |
| Browser | chrome 121 |

**Comment by skmbw** [comment]
错误出现在文件st.component.mjs的113行，this.cms = inject(NzContextMenuService);

**Comment by skmbw** [comment]
就像这样，ModalHelper.createStatic(DataRuleGroupEditComponent......，创建模态框，如果DataRuleGroupEditComponent（模态框要弹出的组件，包含st组件），模态框将无法渲染

**Comment by LingerInside** [comment]
> 就像这样，ModalHelper.createStatic(DataRuleGroupEditComponent......，创建模态框，如果DataRuleGroupEditComponent（模态框要弹出的组件，包含st组件），模态框将无法渲染

使用standalone component，NgModule中imports当前component

```
@Component({
  standalone: true,
  imports: [STModule]
})
```

**Comment by cipchk** [comment]
@skmbw 我也不无重现出你所说的情况 ，png:

<img width="1010" alt="image" src="https://github.com/ng-alain/ng-alain/assets/2987467/5af5506b-ec39-4676-b489-05281630fe4a">

**Comment by skmbw** [comment]
> > 就像这样，ModalHelper.createStatic(DataRuleGroupEditComponent......，创建模态框，如果DataRuleGroupEditComponent（模态框要弹出的组件，包含st组件），模态框将无法渲染
> 
> 使用standalone component，NgModule中imports当前component
> 
> ```
> @Component({
>   standalone: true,
>   imports: [STModule]
> })
> ```

你这个方法是对的。组件要在modal中弹出，如果是NgModule组件，且组件中使用了st组件，是会报缺少注入器，无法使用inject方法注入NzContextMenuService，如果不包含st组件，是没问题的；如果组件是standalone组件，包含或者不包含st组件，都是不会报错的。因为我原来很多组件都是NgModule组件，不是standalone组件，一个一个改为standalone，太费时。我的解决方法是，将NzContextMenuService改为使用构造函数注入，不使用inject方法注入，这样就没有问题了。

**Comment by skmbw** [comment]
> @skmbw 我也不无重现出你所说的情况 ，png:
> 
> <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/2987467/310791593-5af5506b-ec39-4676-b489-05281630fe4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NDc5NDgsIm5iZiI6MTcwOTk0NzY0OCwicGF0aCI6Ii8yOTg3NDY3LzMxMDc5MTU5My01YWY1NTA2Yi1lYzM5LTQ2NzYtYjQ4OS0wNTI4MTYzMGZlNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMDEyNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IxNjRlY2I1ZTA0MGExZDY5NjgyZDY3ZWQ5NTVmNjM1ZjUzNWJmMDhlN2ZhMzllYTU0ZDZiZjU2YjNhOTUzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vMrE1rvgE7N2bxTRzippgit2a4_DOwYghdn5ffjrYTU">

组件要在modal中弹出，如果是NgModule组件，且组件中使用了st组件，是会报缺少注入器，无法使用inject方法注入NzContextMenuService，如果不包含st组件，是没问题的；如果组件是standalone组件，包含或者不包含st组件，都是不会报错的。因为我原来很多组件都是NgModule组件，不是standalone组件，一个一个改为standalone，太费时。我的解决方法是，将st.component中的NzContextMenuService改为使用构造函数注入，不使用inject方法注入，这样就没有问题了。那么引申出来一个问题，为什么NzContextMenuService可以使用构造函数注入，不能使用inject方法注入，我就没有深入研究了。

**Comment by rxxy** [comment]
同遇到了，现在改为standalone好了

**Comment by lywzx** [comment]
> > > 就像这样，ModalHelper.createStatic(DataRuleGroupEditComponent......，创建模态框，如果DataRuleGroupEditComponent（模态框要弹出的组件，包含st组件），模态框将无法渲染
> > 
> > 
> > 使用standalone component，NgModule中imports当前component
> > ```
> > @Component({
> >   standalone: true,
> >   imports: [STModule]
> > })
> > ```
> 
> 你这个方法是对的。组件要在modal中弹出，如果是NgModule组件，且组件中使用了st组件，是会报缺少注入器，无法使用inject方法注入NzContextMenuService，如果不包含st组件，是没问题的；如果组件是standalone组件，包含或者不包含st组件，都是不会报错的。因为我原来很多组件都是NgModule组件，不是standalone组件，一个一个改为standalone，太费时。我的解决方法是，将NzContextMenuService改为使用构造函数注入，不使用inject方法注入，这样就没有问题了。

具体是咋改？更改node_modules中的代码？

**Comment by PayHard** [comment]
> @skmbw 我也不无重现出你所说的情况 ，png:
> 
> <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/2987467/310791593-5af5506b-ec39-4676-b489-05281630fe4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyODg1MjcsIm5iZiI6MTcxNzI4ODIyNywicGF0aCI6Ii8yOTg3NDY3LzMxMDc5MTU5My01YWY1NTA2Yi1lYzM5LTQ2NzYtYjQ4OS0wNTI4MTYzMGZlNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMDAzMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY0NTc3MTg5NmM0N2FjZWNmNzdiNGQ4ZjcwMmZkNTI0N2M4ZGI2NmVhM2IzYWFkZDBmNjIzNjgyM2IyNTgxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._MiMoiZ18p58_Z1_s73OrYPa7aMBxKW5OOpivjmbeuM">

我是使用DrawerHelper时报这个错

**Comment by PayHard** [comment]
我是使用DrawerHelper创建时出现这个错误，抽屉中有表格就报错不能弹出，没有表格就可以弹出
![image](https://github.com/ng-alain/ng-alain/assets/21189953/6bac2304-9184-43bb-8c47-92052dc7e35d)

**Comment by cipchk** [comment]
如果是非 `standalone`，可以在根目录中注入 `NzContextMenuServiceModule` 解决。
