### ISSUE TITLE
CascaderWidgetModule  没有找到，导致 动态表单 widget: 'cascader' 级联选择无法使用？

### ISSUE THREAD

**Issue by lvqibin123** [cipchk/ng-alain#2484]
ng-alain 17.1.0  非内置小部件，该如何使用？
按照文档无法使用 非内置小部件；
需要如何操作，才能正常使用？

**Comment by cipchk** [comment]
@lvqibin123 非内置小部件，需要自行注册，见： https://github.com/ng-alain/ng-alain/pull/2485/files

**Comment by lvqibin123** [comment]
收到，解决了，谢谢！



在 2024-03-11 14:18:26，"卡色" ***@***.***> 写道：

@lvqibin123 非内置小部件，需要自行注册，见： https://github.com/ng-alain/ng-alain/pull/2485/files
