### ISSUE TITLE
st resizable 拖拽排序跟排序/过滤太近 容易误触

### ISSUE THREAD

**Issue by saup007** [cipchk/ng-alain#2493]
### Reproduction link
[https://stackblitz.com/edit/angular-witbbe?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.config.ts](https://stackblitz.com/edit/angular-witbbe?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.config.ts)

### Steps to reproduce
`
    {
      title: '邮箱',
      index: 'email',
      width: 150,
      resizable: { minWidth: 150 },
      filter: {
        type: 'keyword',
        placeholder: '输入后按回车搜索',
        fn: (filter, record) => !filter.value || record.email == filter.value,
      },
    },
`

### What is expected?
排序、过滤等button在标题文字的右侧（文字和button在一个span），而不是边框最右侧

### What is actually happening?
排序、过滤和拖拽 在一起，只有鼠标从下往上滑动的时候才会触发排序或过滤，否则都是拖拽 

| Environment | Info |
|---|---|
| ng-alain | 17.2.0 |
| Browser | Chrome 122 |

**Comment by saup007** [comment]
1、
<img width="341" alt="image" src="https://github.com/ng-alain/ng-alain/assets/1343717/b86a772b-1426-4903-8765-17cb45388c53">

 过滤按钮，上面「过滤」、中间「拖拽」、下面「过滤」

误触的机率很大，可以像下面这种，文字与按钮在一起

<img width="231" alt="image" src="https://github.com/ng-alain/ng-alain/assets/1343717/eabaef0a-cb41-4881-ac32-10561a214447">
<img width="425" alt="image" src="https://github.com/ng-alain/ng-alain/assets/1343717/e9ec1013-5ec3-4fa8-829e-41d6d6b75d7a">

2、如果排序和过滤都加上，排序把过滤覆盖了。

`
     // sort: {
      //   compare: (a, b) => a.email - b.email,
      //   default: 'ascend',
      // },
`

**Comment by cipchk** [comment]
拖拽手柄这里有个没法处理就是当存在过滤或排序时，只能出现在操作区域的最左边。
