### ISSUE TITLE
page-header组件如果带路由参数，会匹配不到菜单，导致page-header没有数据

### ISSUE THREAD

**Issue by shimingxy** [cipchk/ng-alain#2497]
### Reproduction link
[https://stackblitz.com/](https://stackblitz.com/)

### Steps to reproduce
路由地址带路由参数

### What is expected?
会匹配不到菜单，导致page-header没有数据

### What is actually happening?
正常显示菜单路径

| Environment | Info |
|---|---|
| ng-alain | 17.3.1 |
| Browser | ALL |

**Comment by cipchk** [comment]
可以设置 `recursiveBreadcrumb` 为 `true`。
