### ISSUE TITLE
tree-select小部分无法支持输入搜索并在下拉项中高亮输入文本

### ISSUE THREAD

**Issue by angela-huang** [cipchk/ng-alain#2499]
### Reproduction link
[https://stackblitz.com/edit/angular-d9cysb?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-d9cysb?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
输入【支付】

### What is expected?
高亮所有【支付】

### What is actually happening?
输入框内文字重叠，下拉菜单也没有高亮文案
![image](https://github.com/ng-alain/ng-alain/assets/11454043/603d5cf8-6fa8-4d50-a2d4-7c898e7008ca)

| Environment | Info |
|---|---|
| ng-alain | 16.2.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
![d6bab733c9d165e7de4ee8dff5c673aa](https://github.com/ng-alain/ng-alain/assets/2987467/484f8461-cdce-4b3f-a8fb-57b840f1d66a)

我这里一切正常。
