### ISSUE TITLE
st data为Observable数据源时，若未complete则st的loading会失效

### ISSUE THREAD

**Issue by zbrongyaozb** [cipchk/ng-alain#2500]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-xu4uvv?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-xu4uvv?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
demo中，数据已经出来，但是loading仍在继续

### What is expected?
loading应该消失

### What is actually happening?
loading仍在继续

| Environment | Info |
|---|---|
| ng-alain | 17.3.1 |
| Browser | edge 126.0.2592.61 |

---
在升级一个旧项目，升级到16版本的时候，发现了这个问题。
查看了14版本和16版本的代码，发现代码从Promise变成了Observable，应该就是finalize导致的。
```
#v14 
 const result = await this.loadData();
 this.setLoading(false);
#v16
this.loadData().pipe(
      finalize(() => this.setLoading(false)),
      ...)
```

**Comment by cipchk** [comment]
是的，是需要外部调用 `complete`。

传递的 `data` 为 `Observate` 时 `st` 内部始终会认为你给的是一个冷 `Observate`，是必须要调用 `next` 后，再调用 `complete` 表示结束请求。

当然，如果你提供的是一个热 `Observate`，你自然自己接管 `loading` 属性了。
