### ISSUE TITLE
st 可选择 checkbox 全选支持选择全部数据（默认只有当前页）

### ISSUE THREAD

**Issue by saup007** [cipchk/ng-alain#2509]
### Reproduction link
[https://stackblitz.com/edit/angular-vfmaj1?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-vfmaj1?file=src%2Fapp%2Fapp.config.ts,src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1、想实现首页全选全部数据
2、其他页只有当前页数据（这个不是必须的，也可以全部数据）

### What is expected?
可以通过参数控制选择全部数据还是当前页数据

### What is actually happening?
只有当前页数据，若自己想实例全部数据得知道当前触发的是选一个，还是选多个，定义一个变量previousItemsState保存上一次选择的数据。

主要怎么知道是点击的‘全选’

| Environment | Info |
|---|---|
| ng-alain | 17.3.1 |
| Browser | Chrome 126 |

**Comment by cipchk** [comment]
主要是 `url` 请求是无状态的，所以只能通过 `change` 自行维护全选数据源。
