### ISSUE TITLE
g2-timeline cannot fully display the value of the y-axis when the value is greater than or equal to six digits.

### ISSUE THREAD

**Issue by shipengqi** [cipchk/ng-alain#2513]
### Reproduction link
[https://stackblitz.com/edit/angular-3c4tve-mrjjup?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-3c4tve-mrjjup?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
set value of y-axis, make the value greater than or equal to six digits.
```typescript
y1: Math.floor(Math.random() * 100) * 10000,
y2: Math.floor(Math.random() * 100) * 10,
```

### What is expected?
The values of y-axis can be displayed in full.

### What is actually happening?
The values of y-axis cannot be displayed in full.

| Environment | Info |
|---|---|
| ng-alain | 18.1.0 |
| Browser | Chrome Version 127.0.6533.89 |

**Comment by shipengqi** [comment]
Add a screenshot for this issue

![image](https://github.com/user-attachments/assets/5a1c2ae7-0255-4cb3-9c89-1f30bd6aca3a)

**Comment by cipchk** [comment]
You can adjust the `padding` parameter: 

```diff
[height]="200"
+ [padding]="[40, 8, 64, 60]"
```

**Comment by shipengqi** [comment]
> You can adjust the `padding` parameter:
> 
> ```diff
> [height]="200"
> + [padding]="[40, 8, 64, 60]"
> ```

Thanks a lot!
