### ISSUE TITLE
没有withJWT

### ISSUE THREAD

**Issue by yedajiang44** [cipchk/ng-alain#2516]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-ahsbs2?file=src%2Fapp%2Fapp.config.ts](https://stackblitz.com/edit/ng-alain-setup-ahsbs2?file=src%2Fapp%2Fapp.config.ts)

### Steps to reproduce
打开链接

### What is expected?
编译正常

### What is actually happening?
withJWT不存在

| Environment | Info |
|---|---|
| ng-alain | 18.1.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
抱歉，这是一个文档的错误，使用 JWT 应该调用拦截器：

```diff
- provideHttpClient(withInterceptors([...(environment.interceptorFns ?? []), authSimpleInterceptor, defaultInterceptor])),
+ provideHttpClient(withInterceptors([...(environment.interceptorFns ?? []), authJWTInterceptor, defaultInterceptor])),
```

**Comment by yedajiang44** [comment]
但是依然报401，api是不需要鉴权的

**Comment by cipchk** [comment]
不需要鉴权的部分，可以加上 `ALLOW_ANONYMOUS`，例如：https://github.com/ng-alain/ng-alain/blob/master/src/app/core/startup/startup.service.ts#L40

**Comment by yedajiang44** [comment]
可以根据服务器返回的状态码进行处理吗？前端对url主动进行拦截的方式感觉有些不妥，有些权限是后端根据业务动态判断是否401的

**Comment by cipchk** [comment]
非明确的情况下，你可以自行处理，比如：

https://github.com/ng-alain/ng-alain/blob/master/src/app/core/net/default.interceptor.ts#L39
