### ISSUE TITLE
顶部菜单折叠开关html标签使用与其他功能按钮不一致，导致图标大小不协调

### ISSUE THREAD

**Issue by zengqinglei** [cipchk/ng-alain#2519]
### Reproduction link
[https://github.com/ng-alain/delon/blob/master/src/dev/layout.component.ts#L65-L72](https://github.com/ng-alain/delon/blob/master/src/dev/layout.component.ts#L65-L72)

### Steps to reproduce
打开连接：https://ng-alain.com/dev/home，发现头部折叠按钮左边图标 和 Default、Bus左边的图标按钮大小不一致

### What is expected?
头部折叠按钮标签改用<i nz-icon nzType="menu"></i>

### What is actually happening?
头部折叠按钮左边图标 和 Default、Bus左边的图标按钮大小要一致

| Environment | Info |
|---|---|
| ng-alain | 18.1.0 |
| Browser | chrome 126.0.6478.127 |

---
新创建的项目，也是同样如此

**Comment by cipchk** [comment]
Head 的图标默认为 `@alain-default-header-icon-fs` ，侧边栏为 `@alain-default-aside-nav-fs`，默认情况下 head 会略大于侧边栏，你可以通过 `theme.less` 自行调整。

**Comment by zengqinglei** [comment]
> Head 的图标默认为 `@alain-default-header-icon-fs` ，侧边栏为 `@alain-default-aside-nav-fs`，默认情况下 head 会略大于侧边栏，你可以通过 `theme.less` 自行调整。

我说的不是这个意思，我的意思是下图中2个图标大小不一致，没有找到参数可以调整：
![image](https://github.com/user-attachments/assets/443a48a4-3e36-4ea6-bbda-890599636fbd)

**Comment by zengqinglei** [comment]
@cipchk 我检查了预览界面，大小仍然不一致；
同时我也查看了你们提交的源码，发现应该是针对这个是无效的，麻烦在确认下：
![image](https://github.com/user-attachments/assets/b71530c0-3c75-4a02-8348-43e6663ea42d)
