### ISSUE TITLE
select连续点击label会出现两个下拉框效果

### ISSUE THREAD

**Issue by Booom007** [cipchk/ng-alain#2522]
### Reproduction link
[https://private-user-images.githubusercontent.com/39211747/375725115-47623f44-4703-4504-b9d1-90f9c160b934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDM4MDIsIm5iZiI6MTcyODY0MzUwMiwicGF0aCI6Ii8zOTIxMTc0Ny8zNzU3MjUxMTUtNDc2MjNmNDQtNDcwMy00NTA0LWI5ZDEtOTBmOWMxNjBiOTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEwNDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTQ1ZmNiMDRlYWIwNjQ0ZDNhMDg1YTFkODA5MWExNDhmMmM5NDBmMmNkYmI1M2UxNjE4Y2U2MmYyYTk4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UeQcpzrehWvZ_qY8o9QpMASNgA0A8EUYD9ZwczmtFzc](https://private-user-images.githubusercontent.com/39211747/375725115-47623f44-4703-4504-b9d1-90f9c160b934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDM4MDIsIm5iZiI6MTcyODY0MzUwMiwicGF0aCI6Ii8zOTIxMTc0Ny8zNzU3MjUxMTUtNDc2MjNmNDQtNDcwMy00NTA0LWI5ZDEtOTBmOWMxNjBiOTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEwNDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTQ1ZmNiMDRlYWIwNjQ0ZDNhMDg1YTFkODA5MWExNDhmMmM5NDBmMmNkYmI1M2UxNjE4Y2U2MmYyYTk4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UeQcpzrehWvZ_qY8o9QpMASNgA0A8EUYD9ZwczmtFzc)

### Steps to reproduce
连续点击select组件的label文本

### What is expected?
只出现一次下拉框或者下拉框已经弹出能够关闭、收起能够弹出

### What is actually happening?
会一直弹出下拉框，并且快速点击会出现两个下拉框的效果

| Environment | Info |
|---|---|
| ng-alain | 18.2.0 |
| Browser | Google Chrome 129.0.6668.90 |

**Comment by cipchk** [comment]
这看起来像是 `nz-select` 隐藏动画与开始动画的冲突，但这并不影响操作，见 GIF：

![Untitled](https://github.com/user-attachments/assets/6b47decb-dd00-44ea-9054-ac68540f1459)
