### ISSUE TITLE
Observable cache characteristics cause the application information after logging in with Token

### ISSUE THREAD

**Issue by xingkoo** [cipchk/ng-alain#2524]
### Reproduction link
[https://github.com/ng-alain/ng-alain/blob/master/src/app/core/startup/startup.service.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/core/startup/startup.service.ts)

### Steps to reproduce
通过CLI创建最新版本的应用，在startup.service.ts文件中可见代码。

### What is expected?
fix it

### What is actually happening?
登陆成功后，重新加载应用信息时，即可得到用户相关信息。

| Environment | Info |
|---|---|
| ng-alain | 18.2.0 |
| Browser | Chrome |

---
默认使用 `private appData$ = this.httpClient.get('api')`来发起请求，会导致当登陆页面登陆成功后，再次调用 startup.service的load方法时，因为Observable的缓存特性，无法把刚刚写入到Tokenservice中的token加载到Header中去。

原始代码是：
```
  private appData$ = this.httpClient.get('./assets/tmp/app-data.json').pipe(
    catchError((res: NzSafeAny) => {
      console.warn(`StartupService.load: Network request failed`, res);
      setTimeout(() => this.router.navigateByUrl(`/exception/500`));
      return of({});
    })
  );
```
需要修改为一个方法，
```
  private getAppData(): Observable<any> {
    return this.httpClient.get('./assets/tmp/app-data.json', {
      context: new HttpContext().set(ALLOW_ANONYMOUS, this.tokenService.get()?.token ? false : true)
    }).pipe(
      catchError((res: NzSafeAny) => {
        console.warn(`StartupService.load: Network request failed`, res);
        setTimeout(() => this.router.navigateByUrl(`/exception/500`));
        return of({});
      })
    );
  }
```

**Comment by cipchk** [comment]
事实上主要原因还是 `@delon/auth` 的 [ignores](https://github.com/ng-alain/delon/blob/master/packages/auth/src/auth.config.ts#L13) 默认值不符合 `./assets/` 的 URL 规则，如果你将请求更改为符合 URL 规则的话（例如 `/assets`）那么问题就影刃而解。
