### ISSUE TITLE
sf tree-select多选模式下框内没有被选中内容

### ISSUE THREAD

**Issue by MockAs** [cipchk/ng-alain#2545]
### Reproduction link
[https://github.com/ng-alain/ng-alain](https://github.com/ng-alain/ng-alain)

### Steps to reproduce
- sf配置一个tree-select，将multiple或者checkable设为true就能复现

目前的文档官网就是例子 https://ng-alain.com/form/tree-select/zh

### What is expected?
在选框内能够显示已选项

zorro原生组件没有这个问题  https://ng.ant.design/components/tree-select/zh

### What is actually happening?
选框内一片空白没有内容

| Environment | Info |
|---|---|
| ng-alain | 18.3.0 |
| Browser | Chrome 131.0.6778.140 (Official Build) (x86_64) |

**Comment by TanYiBing** [comment]
这个问题出在哪，解决了吗

**Comment by duqian42707** [comment]
解决了，给maxTagCount属性设置上值就行了
```js
  deptIds: {
    type: 'string',
    title: '部门',
    ui: {
      widget: 'tree-select',
      multiple: true,
      maxTagCount: 3,  // <===== 这里
      asyncData: () => this.sysDeptService.loadDeptTree(),
    } as SFTreeSelectWidgetSchema,
  },
```
